/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AnalyticsDetailsResponseAnalyticsDetailsInner } from './analytics-details-response-analytics-details-inner';

/**
 * 
 * @export
 * @interface AnalyticsDetailsResponse
 */
export interface AnalyticsDetailsResponse {
    /**
     * The queried start date
     * @type {string}
     * @memberof AnalyticsDetailsResponse
     */
    'from'?: string;
    /**
     * The queried end date.
     * @type {string}
     * @memberof AnalyticsDetailsResponse
     */
    'to'?: string;
    /**
     * The next page token is used to paginate through large result sets. A next page token will be returned whenever the set of available results exceeds the current page size. The expiration period for this token is 15 minutes.
     * @type {string}
     * @memberof AnalyticsDetailsResponse
     */
    'next_page_token'?: string;
    /**
     * The number of records returned within a single API call.
     * @type {number}
     * @memberof AnalyticsDetailsResponse
     */
    'page_size'?: number;
    /**
     * The total number of all the records available across pages.
     * @type {number}
     * @memberof AnalyticsDetailsResponse
     */
    'total_records'?: number;
    /**
     * Analytics Detail.
     * @type {Array<AnalyticsDetailsResponseAnalyticsDetailsInner>}
     * @memberof AnalyticsDetailsResponse
     */
    'analytics_details'?: Array<AnalyticsDetailsResponseAnalyticsDetailsInner>;
}

