/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ArchivingMeetingFilesListResponseMeetingsInner } from './archiving-meeting-files-list-response-meetings-inner';

/**
 * 
 * @export
 * @interface ArchivingMeetingFilesListResponse
 */
export interface ArchivingMeetingFilesListResponse {
    /**
     * The queried start date.
     * @type {string}
     * @memberof ArchivingMeetingFilesListResponse
     */
    'from'?: string;
    /**
     * Information about the meeting or webinar.
     * @type {Array<ArchivingMeetingFilesListResponseMeetingsInner>}
     * @memberof ArchivingMeetingFilesListResponse
     */
    'meetings'?: Array<ArchivingMeetingFilesListResponseMeetingsInner>;
    /**
     * Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token\'s expiration period is 15 minutes.   **Note:** if you use `next_page_token` as a parameter, your other request parameters should be changeless to make sure that the large result set is what you want. For example, if your `to` parameter is for a future time, Zoom resets this value to the current time and returns this value in the response body, along with the `next_page_token` value. Use these same `to` and `next_page_token` values in requests for the remaining results set; otherwise you will get an invalid token error.
     * @type {string}
     * @memberof ArchivingMeetingFilesListResponse
     */
    'next_page_token'?: string;
    /**
     * The number of records returned within a single API call.
     * @type {number}
     * @memberof ArchivingMeetingFilesListResponse
     */
    'page_size'?: number;
    /**
     * The queried end date.
     * @type {string}
     * @memberof ArchivingMeetingFilesListResponse
     */
    'to'?: string;
    /**
     * The total number of returned meeting records.
     * @type {number}
     * @memberof ArchivingMeetingFilesListResponse
     */
    'total_records'?: number;
}

