/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Statistics about archive files, by file extension.
 * @export
 * @interface ArchivingGetStatisticsResponseStatisticByFileExtension
 */
export interface ArchivingGetStatisticsResponseStatisticByFileExtension {
    /**
     * The number of mp4 files.
     * @type {number}
     * @memberof ArchivingGetStatisticsResponseStatisticByFileExtension
     */
    'mp4_file_count'?: number;
    /**
     * The number of m4a files.
     * @type {number}
     * @memberof ArchivingGetStatisticsResponseStatisticByFileExtension
     */
    'm4a_file_count'?: number;
    /**
     * The number of txt files.
     * @type {number}
     * @memberof ArchivingGetStatisticsResponseStatisticByFileExtension
     */
    'txt_file_count'?: number;
    /**
     * The number of json files.
     * @type {number}
     * @memberof ArchivingGetStatisticsResponseStatisticByFileExtension
     */
    'json_file_count'?: number;
    /**
     * The number of vtt files.
     * @type {number}
     * @memberof ArchivingGetStatisticsResponseStatisticByFileExtension
     */
    'vtt_file_count'?: number;
}

