/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CloudRecordingListRegistrationQuestionsResponseCustomQuestionsInner
 */
export interface CloudRecordingListRegistrationQuestionsResponseCustomQuestionsInner {
    /**
     * Title of the question.
     * @type {string}
     * @memberof CloudRecordingListRegistrationQuestionsResponseCustomQuestionsInner
     */
    'title'?: string;
    /**
     * Answer choices for the question. Can not be used with Short answer type.
     * @type {Array<string>}
     * @memberof CloudRecordingListRegistrationQuestionsResponseCustomQuestionsInner
     */
    'answers'?: Array<string>;
    /**
     * State whether registrants are required to answer custom questions or not.
     * @type {boolean}
     * @memberof CloudRecordingListRegistrationQuestionsResponseCustomQuestionsInner
     */
    'required'?: boolean;
    /**
     * The type of registration question and answers.
     * @type {string}
     * @memberof CloudRecordingListRegistrationQuestionsResponseCustomQuestionsInner
     */
    'type'?: CloudRecordingListRegistrationQuestionsResponseCustomQuestionsInnerTypeEnum;
}

type CloudRecordingListRegistrationQuestionsResponseCustomQuestionsInnerTypeEnum = 'short' | 'single' | 'multiple'


