/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CloudRecordingListRegistrantsResponseRegistrantsInnerCustomQuestionsInner } from './cloud-recording-list-registrants-response-registrants-inner-custom-questions-inner';

/**
 *  Registrant.
 * @export
 * @interface CloudRecordingListRegistrantsResponseRegistrantsInner
 */
export interface CloudRecordingListRegistrantsResponseRegistrantsInner {
    /**
     * The registrant\'s ID.
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'id'?: string;
    /**
     * The registrant\'s address.
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'address'?: string;
    /**
     * The registrant\'s city.
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'city'?: string;
    /**
     * The registrant\'s questions and comments.
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'comments'?: string;
    /**
     * The registrant\'s two-letter [country code](https://marketplace.zoom.us/docs/api-reference/other-references/abbreviation-lists#countries).
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'country'?: string;
    /**
     * Information about custom questions.
     * @type {Array<CloudRecordingListRegistrantsResponseRegistrantsInnerCustomQuestionsInner>}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'custom_questions'?: Array<CloudRecordingListRegistrantsResponseRegistrantsInnerCustomQuestionsInner>;
    /**
     * The registrant\'s email address. See [Email address display rules](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#email-address) for return value details.
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'email': string;
    /**
     * The registrant\'s first name.
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'first_name': string;
    /**
     * The registrant\'s industry.
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'industry'?: string;
    /**
     * The registrant\'s job title.
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'job_title'?: string;
    /**
     * The registrant\'s last name.
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'last_name'?: string;
    /**
     * The registrant\'s number of employees:  * `1-20`  * `21-50`  * `51-100`  * `101-250`  * `251-500`  * `501-1,000`  * `1,001-5,000`  * `5,001-10,000`  * `More than 10,000`
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'no_of_employees'?: CloudRecordingListRegistrantsResponseRegistrantsInnerNoOfEmployeesEnum;
    /**
     * The registrant\'s organization.
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'org'?: string;
    /**
     * The registrant\'s phone number.
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'phone'?: string;
    /**
     * The registrant\'s purchasing time frame:  * `Within a month`  * `1-3 months`  * `4-6 months`  * `More than 6 months`  * `No timeframe`
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'purchasing_time_frame'?: CloudRecordingListRegistrantsResponseRegistrantsInnerPurchasingTimeFrameEnum;
    /**
     * The registrant\'s role in the purchase process:  * `Decision Maker`  * `Evaluator/Recommender`  * `Influencer`  * `Not involved`
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'role_in_purchase_process'?: CloudRecordingListRegistrantsResponseRegistrantsInnerRoleInPurchaseProcessEnum;
    /**
     * The registrant\'s state or province.
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'state'?: string;
    /**
     * The registrant\'s status:  * `approved` &mdash; Registrant is approved.  * `denied` &mdash; Registrant is denied.  * `pending` &mdash; Registrant is waiting for approval.
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'status'?: CloudRecordingListRegistrantsResponseRegistrantsInnerStatusEnum;
    /**
     * The registrant\'s ZIP or postal code.
     * @type {string}
     * @memberof CloudRecordingListRegistrantsResponseRegistrantsInner
     */
    'zip'?: string;
}

type CloudRecordingListRegistrantsResponseRegistrantsInnerNoOfEmployeesEnum = '' | '1-20' | '21-50' | '51-100' | '101-250' | '251-500' | '501-1,000' | '1,001-5,000' | '5,001-10,000' | 'More than 10,000'
type CloudRecordingListRegistrantsResponseRegistrantsInnerPurchasingTimeFrameEnum = '' | 'Within a month' | '1-3 months' | '4-6 months' | 'More than 6 months' | 'No timeframe'
type CloudRecordingListRegistrantsResponseRegistrantsInnerRoleInPurchaseProcessEnum = '' | 'Decision Maker' | 'Evaluator/Recommender' | 'Influencer' | 'Not involved'
type CloudRecordingListRegistrantsResponseRegistrantsInnerStatusEnum = 'approved' | 'denied' | 'pending'


