/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CloudRecordingListRecordingsResponseMeetingsInner } from './cloud-recording-list-recordings-response-meetings-inner';

/**
 * The pagination object.
 * @export
 * @interface CloudRecordingListRecordingsResponse
 */
export interface CloudRecordingListRecordingsResponse {
    /**
     * The start date.
     * @type {string}
     * @memberof CloudRecordingListRecordingsResponse
     */
    'from'?: string;
    /**
     * The end date.
     * @type {string}
     * @memberof CloudRecordingListRecordingsResponse
     */
    'to'?: string;
    /**
     * The next page token paginates through a large set of results. A next page token returns whenever the set of available results exceeds the current page size. The expiration period for this token is 15 minutes.
     * @type {string}
     * @memberof CloudRecordingListRecordingsResponse
     */
    'next_page_token'?: string;
    /**
     * The number of pages returned for the request made.
     * @type {number}
     * @memberof CloudRecordingListRecordingsResponse
     */
    'page_count'?: number;
    /**
     * The number of records returned within a single API call.
     * @type {number}
     * @memberof CloudRecordingListRecordingsResponse
     */
    'page_size'?: number;
    /**
     * The number of all records available across pages.
     * @type {number}
     * @memberof CloudRecordingListRecordingsResponse
     */
    'total_records'?: number;
    /**
     * List of recordings.
     * @type {Array<CloudRecordingListRecordingsResponseMeetingsInner>}
     * @memberof CloudRecordingListRecordingsResponse
     */
    'meetings'?: Array<CloudRecordingListRecordingsResponseMeetingsInner>;
}

