/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CloudRecordingUpdateSettingsRequest
 */
export interface CloudRecordingUpdateSettingsRequest {
    /**
     * The approval type for the registration.     `0`- Automatically approve the registration when a user registers.     `1` - Manually approve or deny the registration of a user.     `2` - No registration required to view the recording.
     * @type {number}
     * @memberof CloudRecordingUpdateSettingsRequest
     */
    'approval_type'?: CloudRecordingUpdateSettingsRequestApprovalTypeEnum;
    /**
     * The authentication domains.
     * @type {string}
     * @memberof CloudRecordingUpdateSettingsRequest
     */
    'authentication_domains'?: string;
    /**
     * The authentication options.
     * @type {string}
     * @memberof CloudRecordingUpdateSettingsRequest
     */
    'authentication_option'?: string;
    /**
     * This field determines whether the registration is required to view the recording.
     * @type {boolean}
     * @memberof CloudRecordingUpdateSettingsRequest
     */
    'on_demand'?: boolean;
    /**
     * This field enables passcode protection for the recording by setting a passcode.   The passcode must have a minimum of **eight** characters with a mix of numbers, letters and special characters.          **Note:** If the account owner or the admin has set minimum passcode strength requirements for recordings through Account Settings, the passcode value provided here must meet those requirements.         If the requirements are enabled, you can view those requirements by calling either the [**Get user settings**](/api-reference/zoom-api/methods#operation/userSettings) API or the [**Get account settings**](/api-reference/zoom-api/ma#operation/accountSettings) API.
     * @type {string}
     * @memberof CloudRecordingUpdateSettingsRequest
     */
    'password'?: string;
    /**
     * This field indicates that only authenticated users can view.
     * @type {boolean}
     * @memberof CloudRecordingUpdateSettingsRequest
     */
    'recording_authentication'?: boolean;
    /**
     * This field sends an email to host when someone registers to view the recording. This setting applies for On-demand recordings only.
     * @type {boolean}
     * @memberof CloudRecordingUpdateSettingsRequest
     */
    'send_email_to_host'?: boolean;
    /**
     * This field determines how the meeting recording is shared.
     * @type {string}
     * @memberof CloudRecordingUpdateSettingsRequest
     */
    'share_recording'?: CloudRecordingUpdateSettingsRequestShareRecordingEnum;
    /**
     * This field shows social share buttons on registration page. This setting applies for On-demand recordings only.
     * @type {boolean}
     * @memberof CloudRecordingUpdateSettingsRequest
     */
    'show_social_share_buttons'?: boolean;
    /**
     * The name of the recording.
     * @type {string}
     * @memberof CloudRecordingUpdateSettingsRequest
     */
    'topic'?: string;
    /**
     * This field determines whether a viewer can download the recording file or not.
     * @type {boolean}
     * @memberof CloudRecordingUpdateSettingsRequest
     */
    'viewer_download'?: boolean;
}

type CloudRecordingUpdateSettingsRequestApprovalTypeEnum = 0 | 1 | 2
type CloudRecordingUpdateSettingsRequestShareRecordingEnum = 'publicly' | 'internally' | 'none'


