/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DevicesGetZpaVersionInfoResponseFirmwareVersionsInner } from './devices-get-zpa-version-info-response-firmware-versions-inner';

/**
 * Information about the version list.
 * @export
 * @interface DevicesGetZpaVersionInfoResponse
 */
export interface DevicesGetZpaVersionInfoResponse {
    /**
     * List of firmware that can be upgraded.
     * @type {Array<DevicesGetZpaVersionInfoResponseFirmwareVersionsInner>}
     * @memberof DevicesGetZpaVersionInfoResponse
     */
    'firmware_versions'?: Array<DevicesGetZpaVersionInfoResponseFirmwareVersionsInner>;
    /**
     * List of app versions that can be upgraded.
     * @type {Array<string>}
     * @memberof DevicesGetZpaVersionInfoResponse
     */
    'app_versions'?: Array<string>;
}

