/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The information about the device.
 * @export
 * @interface DevicesListResponseDevicesInner
 */
export interface DevicesListResponseDevicesInner {
    /**
     * Unique identifier of the device.
     * @type {string}
     * @memberof DevicesListResponseDevicesInner
     */
    'device_id'?: string;
    /**
     * The name of the device.
     * @type {string}
     * @memberof DevicesListResponseDevicesInner
     */
    'device_name'?: string;
    /**
     * The mac address of the device.
     * @type {string}
     * @memberof DevicesListResponseDevicesInner
     */
    'mac_address'?: string;
    /**
     * The device\'s serial number.
     * @type {string}
     * @memberof DevicesListResponseDevicesInner
     */
    'serial_number'?: string;
    /**
     * The device\'s manufacturer.
     * @type {string}
     * @memberof DevicesListResponseDevicesInner
     */
    'vendor'?: string;
    /**
     * The device\'s model.
     * @type {string}
     * @memberof DevicesListResponseDevicesInner
     */
    'model'?: string;
    /**
     * The device\'s platform.
     * @type {string}
     * @memberof DevicesListResponseDevicesInner
     */
    'platform_os'?: string;
    /**
     * App version of Zoom Rooms.
     * @type {string}
     * @memberof DevicesListResponseDevicesInner
     */
    'app_version'?: string;
    /**
     * The name of the tag.
     * @type {string}
     * @memberof DevicesListResponseDevicesInner
     */
    'tag'?: string;
    /**
     * Whether the device enrolled in ZDM (Zoom Device Management).
     * @type {boolean}
     * @memberof DevicesListResponseDevicesInner
     */
    'enrolled_in_zdm'?: boolean;
    /**
     * Whether the device connected to ZDM (Zoom Device Management).
     * @type {boolean}
     * @memberof DevicesListResponseDevicesInner
     */
    'connected_to_zdm'?: boolean;
    /**
     * id of the Zoom Room.
     * @type {string}
     * @memberof DevicesListResponseDevicesInner
     */
    'room_id'?: string;
    /**
     * Name of the Zoom Room.
     * @type {string}
     * @memberof DevicesListResponseDevicesInner
     */
    'room_name'?: string;
    /**
     * Filter devices by device type.     Device Type:    `-1` - All Zoom Room device(0,1,2,3,4,6).    `0` - Zoom Rooms Computer.    `1` - Zoom Rooms Controller.    `2` - Zoom Rooms Scheduling Display.    `3` - Zoom Rooms Control System.    `4` -  Zoom Rooms Whiteboard.    `5` - Zoom Phone Appliance.    `6` - Zoom Rooms Computer (with Controller).
     * @type {number}
     * @memberof DevicesListResponseDevicesInner
     */
    'device_type'?: DevicesListResponseDevicesInnerDeviceTypeEnum;
    /**
     * The version of the SDK.
     * @type {string}
     * @memberof DevicesListResponseDevicesInner
     */
    'skd_version'?: string;
    /**
     * Filter devices by status.      Device Status:    `0` - offline.    `1` - online.    `-1` - unlink
     * @type {number}
     * @memberof DevicesListResponseDevicesInner
     */
    'device_status'?: DevicesListResponseDevicesInnerDeviceStatusEnum;
    /**
     * The time when device was online last time.
     * @type {string}
     * @memberof DevicesListResponseDevicesInner
     */
    'last_online'?: string;
    /**
     * The owner of the phone device
     * @type {string}
     * @memberof DevicesListResponseDevicesInner
     */
    'user_email'?: string;
}

type DevicesListResponseDevicesInnerDeviceTypeEnum = 0 | 1 | 2 | 3 | 4 | 5 | 6
type DevicesListResponseDevicesInnerDeviceStatusEnum = -1 | 0 | 1


