/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The H.323/SIP device object.
 * @export
 * @interface H323DevicesUpdateDeviceInfoRequest
 */
export interface H323DevicesUpdateDeviceInfoRequest {
    /**
     * Device encryption:    `auto` - auto.    `yes` - yes.    `no` - no.
     * @type {string}
     * @memberof H323DevicesUpdateDeviceInfoRequest
     */
    'encryption': H323DevicesUpdateDeviceInfoRequestEncryptionEnum;
    /**
     * Device IP.
     * @type {string}
     * @memberof H323DevicesUpdateDeviceInfoRequest
     */
    'ip': string;
    /**
     * Device name.
     * @type {string}
     * @memberof H323DevicesUpdateDeviceInfoRequest
     */
    'name': string;
    /**
     * Device protocol:    `H.323` - H.323.    `SIP` - SIP.
     * @type {string}
     * @memberof H323DevicesUpdateDeviceInfoRequest
     */
    'protocol': H323DevicesUpdateDeviceInfoRequestProtocolEnum;
}

type H323DevicesUpdateDeviceInfoRequestEncryptionEnum = 'auto' | 'true' | 'false'
type H323DevicesUpdateDeviceInfoRequestProtocolEnum = 'H.323' | 'SIP'


