/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about the meeting\'s local archive token.
 * @export
 * @interface MeetingsGetMeetingArchiveTokenForLocalArchivingResponse
 */
export interface MeetingsGetMeetingArchiveTokenForLocalArchivingResponse {
    /**
     * The number of seconds the archive token is valid for before it expires. This value always returns `120`.
     * @type {number}
     * @memberof MeetingsGetMeetingArchiveTokenForLocalArchivingResponse
     */
    'expire_in'?: MeetingsGetMeetingArchiveTokenForLocalArchivingResponseExpireInEnum;
    /**
     * The archive token.
     * @type {string}
     * @memberof MeetingsGetMeetingArchiveTokenForLocalArchivingResponse
     */
    'token'?: string;
}

type MeetingsGetMeetingArchiveTokenForLocalArchivingResponseExpireInEnum = 120


