/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MeetingsUpdateDetailsRequestSettingsResourcesInner
 */
export interface MeetingsUpdateDetailsRequestSettingsResourcesInner {
    /**
     * The resource type.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettingsResourcesInner
     */
    'resource_type'?: MeetingsUpdateDetailsRequestSettingsResourcesInnerResourceTypeEnum;
    /**
     * The resource ID.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettingsResourcesInner
     */
    'resource_id'?: string;
    /**
     * The permission levels for users to access the whiteboard.  * `editor` - Users with link access can edit the board.  * `commenter` - Users with link access can comment on the board.  * `viewer` - Users with link access can view the board.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettingsResourcesInner
     */
    'permission_level'?: MeetingsUpdateDetailsRequestSettingsResourcesInnerPermissionLevelEnum;
}

type MeetingsUpdateDetailsRequestSettingsResourcesInnerResourceTypeEnum = 'whiteboard'
type MeetingsUpdateDetailsRequestSettingsResourcesInnerPermissionLevelEnum = 'editor' | 'commenter' | 'viewer'


