/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about the **Enable continuous meeting chat** feature.
 * @export
 * @interface MeetingsGetDetailsResponseSettingsContinuousMeetingChat
 */
export interface MeetingsGetDetailsResponseSettingsContinuousMeetingChat {
    /**
     * Whether to enable the **Enable continuous meeting chat** setting.
     * @type {boolean}
     * @memberof MeetingsGetDetailsResponseSettingsContinuousMeetingChat
     */
    'enable'?: boolean;
    /**
     * Whether to enable the **Automatically add invited external users** setting.
     * @type {boolean}
     * @memberof MeetingsGetDetailsResponseSettingsContinuousMeetingChat
     */
    'auto_add_invited_external_users'?: boolean;
    /**
     * The channel\'s ID.
     * @type {string}
     * @memberof MeetingsGetDetailsResponseSettingsContinuousMeetingChat
     */
    'channel_id'?: string;
}

