/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsCreateInviteLinksRequestAttendeesInner } from './meetings-create-invite-links-request-attendees-inner';

/**
 * Invite Links
 * @export
 * @interface MeetingsCreateInviteLinksRequest
 */
export interface MeetingsCreateInviteLinksRequest {
    /**
     * The attendees list.
     * @type {Array<MeetingsCreateInviteLinksRequestAttendeesInner>}
     * @memberof MeetingsCreateInviteLinksRequest
     */
    'attendees'?: Array<MeetingsCreateInviteLinksRequestAttendeesInner>;
    /**
     * The invite link\'s expiration time, in seconds.   This value defaults to `7200`.
     * @type {number}
     * @memberof MeetingsCreateInviteLinksRequest
     */
    'ttl'?: number;
}

