/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MeetingsGetLivestreamDetailsResponse
 */
export interface MeetingsGetLivestreamDetailsResponse {
    /**
     * Live streaming page URL. This is the URL using which anyone can view the livestream of the meeting.
     * @type {string}
     * @memberof MeetingsGetLivestreamDetailsResponse
     */
    'page_url'?: string;
    /**
     * Stream Key.
     * @type {string}
     * @memberof MeetingsGetLivestreamDetailsResponse
     */
    'stream_key'?: string;
    /**
     * Stream URL.
     * @type {string}
     * @memberof MeetingsGetLivestreamDetailsResponse
     */
    'stream_url'?: string;
    /**
     * The number of pixels in each dimension that the video camera can display.
     * @type {string}
     * @memberof MeetingsGetLivestreamDetailsResponse
     */
    'resolution'?: string;
}

