/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsGetRegistrantDetailsResponseCustomQuestionsInner } from './meetings-get-registrant-details-response-custom-questions-inner';

/**
 *  Registrant.
 * @export
 * @interface MeetingsGetRegistrantDetailsResponse
 */
export interface MeetingsGetRegistrantDetailsResponse {
    /**
     * 
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'id'?: string;
    /**
     * The registrant\'s address.
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'address'?: string;
    /**
     * The registrant\'s city.
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'city'?: string;
    /**
     * The registrant\'s questions and comments.
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'comments'?: string;
    /**
     * The registrant\'s two-letter [country code](https://developers.zoom.us/docs/api/rest/other-references/abbreviation-lists/#countries).
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'country'?: string;
    /**
     * Information about custom questions.
     * @type {Array<MeetingsGetRegistrantDetailsResponseCustomQuestionsInner>}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'custom_questions'?: Array<MeetingsGetRegistrantDetailsResponseCustomQuestionsInner>;
    /**
     * The registrant\'s email address. See [Email address display rules](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#email-address-display-rules) for return value details.
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'email': string;
    /**
     * The registrant\'s first name.
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'first_name': string;
    /**
     * The registrant\'s industry.
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'industry'?: string;
    /**
     * The registrant\'s job title.
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'job_title'?: string;
    /**
     * The registrant\'s last name.
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'last_name'?: string;
    /**
     * The registrant\'s number of employees.  * `1-20`  * `21-50`  * `51-100`  * `101-250`  * `251-500`  * `501-1,000`  * `1,001-5,000`  * `5,001-10,000`  * `More than 10,000`
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'no_of_employees'?: MeetingsGetRegistrantDetailsResponseNoOfEmployeesEnum;
    /**
     * The registrant\'s organization.
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'org'?: string;
    /**
     * The registrant\'s phone number.
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'phone'?: string;
    /**
     * The registrant\'s purchasing time frame.  * `Within a month`  * `1-3 months`  * `4-6 months`  * `More than 6 months`  * `No timeframe`
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'purchasing_time_frame'?: MeetingsGetRegistrantDetailsResponsePurchasingTimeFrameEnum;
    /**
     * The registrant\'s role in the purchase process.  * `Decision Maker`  * `Evaluator/Recommender`  * `Influencer`  * `Not involved`
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'role_in_purchase_process'?: MeetingsGetRegistrantDetailsResponseRoleInPurchaseProcessEnum;
    /**
     * The registrant\'s state or province.
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'state'?: string;
    /**
     * The registrant\'s registration status. * `approved` - The registrant is approved to join the meeting.  * `pending` - The registrant\'s registration is pending. * `denied` - The registrant was declined to join the meeting.
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'status'?: MeetingsGetRegistrantDetailsResponseStatusEnum;
    /**
     * The registrant\'s ZIP or postal code.
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'zip'?: string;
    /**
     * The registrant\'s registration date and time.
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'create_time'?: string;
    /**
     * The URL with which the approved registrant can join the meeting.
     * @type {string}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'join_url'?: string;
    /**
     * The participant PIN code is used to authenticate audio participants before they join the meeting.
     * @type {number}
     * @memberof MeetingsGetRegistrantDetailsResponse
     */
    'participant_pin_code'?: number;
}

type MeetingsGetRegistrantDetailsResponseNoOfEmployeesEnum = '' | '1-20' | '21-50' | '51-100' | '101-250' | '251-500' | '501-1,000' | '1,001-5,000' | '5,001-10,000' | 'More than 10,000'
type MeetingsGetRegistrantDetailsResponsePurchasingTimeFrameEnum = '' | 'Within a month' | '1-3 months' | '4-6 months' | 'More than 6 months' | 'No timeframe'
type MeetingsGetRegistrantDetailsResponseRoleInPurchaseProcessEnum = '' | 'Decision Maker' | 'Evaluator/Recommender' | 'Influencer' | 'Not involved'
type MeetingsGetRegistrantDetailsResponseStatusEnum = 'approved' | 'denied' | 'pending'


