/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsCreateMeetingRequestSettingsApprovedOrDeniedCountriesOrRegions } from './meetings-create-meeting-request-settings-approved-or-denied-countries-or-regions';
import { MeetingsCreateMeetingRequestSettingsAuthenticationExceptionInner } from './meetings-create-meeting-request-settings-authentication-exception-inner';
import { MeetingsCreateMeetingRequestSettingsBreakoutRoom } from './meetings-create-meeting-request-settings-breakout-room';
import { MeetingsCreateMeetingRequestSettingsContinuousMeetingChat } from './meetings-create-meeting-request-settings-continuous-meeting-chat';
import { MeetingsCreateMeetingRequestSettingsLanguageInterpretation } from './meetings-create-meeting-request-settings-language-interpretation';
import { MeetingsCreateMeetingRequestSettingsMeetingInviteesInner } from './meetings-create-meeting-request-settings-meeting-invitees-inner';
import { MeetingsCreateMeetingRequestSettingsResourcesInner } from './meetings-create-meeting-request-settings-resources-inner';
import { MeetingsCreateMeetingRequestSettingsSignLanguageInterpretation } from './meetings-create-meeting-request-settings-sign-language-interpretation';

/**
 * Information about the meeting\'s settings.
 * @export
 * @interface MeetingsCreateMeetingRequestSettings
 */
export interface MeetingsCreateMeetingRequestSettings {
    /**
     * Add additional meeting [data center regions](https://support.zoom.us/hc/en-us/articles/360042411451-Selecting-data-center-regions-for-hosted-meetings-and-webinars). Provide this value as an array of [country codes](https://developers.zoom.us/docs/api/rest/other-references/abbreviation-lists/#countries) for the countries available as data center regions in the [**Account Profile**](https://zoom.us/account/setting) interface but have been opted out of in the [user settings](https://zoom.us/profile).  For example, the data center regions selected in your [**Account Profile**](https://zoom.us/account) are `Europe`, `Hong Kong SAR`, `Australia`, `India`, `Japan`, `China`, `United States`, and `Canada`. However, in the [**My Profile**](https://zoom.us/profile) settings, you did **not** select `India` and `Japan` for meeting and webinar traffic routing.  To include `India` and `Japan` as additional data centers, use the `[IN, TY]` value for this field.
     * @type {Array<string>}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'additional_data_center_regions'?: Array<string>;
    /**
     * Whether to allow attendees to join a meeting from multiple devices. This setting is only applied to meetings with registration enabled.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'allow_multiple_devices'?: boolean;
    /**
     * A semicolon-separated list of the meeting\'s alternative hosts\' email addresses or IDs.
     * @type {string}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'alternative_hosts'?: string;
    /**
     * Whether to send email notifications to alternative hosts. This value defaults to `true`.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'alternative_hosts_email_notification'?: boolean;
    /**
     * Enable meeting registration approval. * `0` - Automatically approve registration. * `1` - Manually approve registration. * `2` - No registration required.  This value defaults to `2`.
     * @type {number}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'approval_type'?: MeetingsCreateMeetingRequestSettingsApprovalTypeEnum;
    /**
     * 
     * @type {MeetingsCreateMeetingRequestSettingsApprovedOrDeniedCountriesOrRegions}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'approved_or_denied_countries_or_regions'?: MeetingsCreateMeetingRequestSettingsApprovedOrDeniedCountriesOrRegions;
    /**
     * How participants join the audio portion of the meeting. * `both` - Both telephony and VoIP.  * `telephony` - Telephony only.  * `voip` - VoIP only.  * `thirdParty` - Third party audio conference.
     * @type {string}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'audio'?: MeetingsCreateMeetingRequestSettingsAudioEnum;
    /**
     * Third party audio conference info.
     * @type {string}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'audio_conference_info'?: string;
    /**
     * The meeting\'s authenticated domains. Only Zoom users whose email address contains an authenticated domain can join the meeting. Comma-separate multiple domains or use a wildcard for listing domains.
     * @type {string}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'authentication_domains'?: string;
    /**
     * A list of participants that can bypass meeting authentication. These participants will receive a unique meeting invite.
     * @type {Array<MeetingsCreateMeetingRequestSettingsAuthenticationExceptionInner>}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'authentication_exception'?: Array<MeetingsCreateMeetingRequestSettingsAuthenticationExceptionInner>;
    /**
     * If the `meeting_authentication` value is `true`, the type of authentication required for users to join a meeting.  To get this value, use the `authentication_options` array\'s `id` value in the [**Get user settings**](https://developers.zoom.us/docs/api-reference/zoom-api/methods#operation/userSettings) API response.
     * @type {string}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'authentication_option'?: string;
    /**
     * The automatic recording settings.  * `local` - Record the meeting locally.  * `cloud` - Record the meeting to the cloud.  * `none` - Auto-recording disabled.  This value defaults to `none`.
     * @type {string}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'auto_recording'?: MeetingsCreateMeetingRequestSettingsAutoRecordingEnum;
    /**
     * 
     * @type {MeetingsCreateMeetingRequestSettingsBreakoutRoom}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'breakout_room'?: MeetingsCreateMeetingRequestSettingsBreakoutRoom;
    /**
     * Indicates the type of calendar integration used to schedule the meeting. * `1` - [Zoom Outlook add-in](https://support.zoom.us/hc/en-us/articles/360031592971-Getting-started-with-Outlook-plugin-and-add-in)  * `2` - [Zoom for Google Workspace add-on](https://support.zoom.us/hc/en-us/articles/360020187492-Using-the-Zoom-for-Google-Workspace-add-on)  Works with the `private_meeting` field to determine whether to share details of meetings or not.
     * @type {number}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'calendar_type'?: MeetingsCreateMeetingRequestSettingsCalendarTypeEnum;
    /**
     * Whether to close registration after the event date. This value defaults to `false`.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'close_registration'?: boolean;
    /**
     * Whether to host the meeting in China (CN). This value defaults to `false`.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     * @deprecated
     */
    'cn_meeting'?: boolean;
    /**
     * The contact email address for meeting registration.
     * @type {string}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'contact_email'?: string;
    /**
     * The contact name for meeting registration.
     * @type {string}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'contact_name'?: string;
    /**
     * Whether to send email notifications to [alternative hosts](https://support.zoom.us/hc/en-us/articles/208220166) and [users with scheduling privileges](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-privilege). This value defaults to `true`.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'email_notification'?: boolean;
    /**
     * The type of [end-to-end (E2EE) encryption](https://support.zoom.us/hc/en-us/articles/360048660871) to use for the meeting.  * `enhanced_encryption` - Enhanced encryption. Encryption is stored in the cloud when you enable this option.  * `e2ee` - End-to-end encryption. The encryption key is stored on your local device and **cannot** be obtained by anyone else. When you use E2EE encryption, [certain features](https://support.zoom.us/hc/en-us/articles/360048660871), such as cloud recording or phone and SIP/H.323 dial-in, are **disabled**.
     * @type {string}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'encryption_type'?: MeetingsCreateMeetingRequestSettingsEncryptionTypeEnum;
    /**
     * Whether to enable the [**Focus Mode** feature](https://support.zoom.us/hc/en-us/articles/360061113751-Using-focus-mode) when the meeting starts.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'focus_mode'?: boolean;
    /**
     * A list of available global dial-in countries.
     * @type {Array<string>}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'global_dial_in_countries'?: Array<string>;
    /**
     * Whether to start meetings with the host video on.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'host_video'?: boolean;
    /**
     * Whether to host the meeting in India (IN). This value defaults to `false`.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     * @deprecated
     */
    'in_meeting'?: boolean;
    /**
     * If the value of the `join_before_host` field is `true`, this field indicates the time limits when a participant can join a meeting before the meeting\'s host.  * `0` - Allow the participant to join the meeting at anytime. * `5` - Allow the participant to join 5 minutes before the meeting\'s start time. * `10` - Allow the participant to join 10 minutes before the meeting\'s start time.
     * @type {number}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'jbh_time'?: MeetingsCreateMeetingRequestSettingsJbhTimeEnum;
    /**
     * Whether participants can join the meeting before its host. This field is only used for scheduled meetings (`2`) or recurring meetings (`3` and `8`). This value defaults to `false`.  If the [**Waiting Room** feature](https://support.zoom.us/hc/en-us/articles/115000332726-Waiting-Room) is enabled, this setting is **disabled**.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'join_before_host'?: boolean;
    /**
     * 
     * @type {MeetingsCreateMeetingRequestSettingsLanguageInterpretation}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'language_interpretation'?: MeetingsCreateMeetingRequestSettingsLanguageInterpretation;
    /**
     * 
     * @type {MeetingsCreateMeetingRequestSettingsSignLanguageInterpretation}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'sign_language_interpretation'?: MeetingsCreateMeetingRequestSettingsSignLanguageInterpretation;
    /**
     * If true, only [authenticated](https://support.zoom.us/hc/en-us/articles/360037117472-Authentication-Profiles-for-Meetings-and-Webinars) users can join the meeting.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'meeting_authentication'?: boolean;
    /**
     * A list of the meeting\'s invitees.
     * @type {Array<MeetingsCreateMeetingRequestSettingsMeetingInviteesInner>}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'meeting_invitees'?: Array<MeetingsCreateMeetingRequestSettingsMeetingInviteesInner>;
    /**
     * Whether to mute participants upon entry.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'mute_upon_entry'?: boolean;
    /**
     * Whether to start meetings with the participant video on.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'participant_video'?: boolean;
    /**
     * Whether to set the meeting as private.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'private_meeting'?: boolean;
    /**
     * Whether to send registrants an email confirmation.  * `true` - Send a confirmation email.  * `false` - Do not send a confirmation email.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'registrants_confirmation_email'?: boolean;
    /**
     * Whether to send registrants email notifications about their registration approval, cancellation, or rejection.  * `true` - Send an email notification. * `false` - Do not send an email notification.   Set this value to `true` to also use the `registrants_confirmation_email` parameter.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'registrants_email_notification'?: boolean;
    /**
     * The meeting\'s registration type.  * `1` - Attendees register once and can attend any meeting occurrence.  * `2` - Attendees must register for each meeting occurrence.  * `3` - Attendees register once and can select one or more meeting occurrences to attend.  This field is only for recurring meetings with fixed times (`8`). This value defaults to `1`.
     * @type {number}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'registration_type'?: MeetingsCreateMeetingRequestSettingsRegistrationTypeEnum;
    /**
     * Whether to include social media sharing buttons on the meeting\'s registration page. This setting is only applied to meetings with registration enabled.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'show_share_button'?: boolean;
    /**
     * Whether to use a [Personal Meeting ID (PMI)](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#understanding-personal-meeting-id-pmi) instead of a generated meeting ID. This field is only used for scheduled meetings (`2`), instant meetings (`1`), or recurring meetings with no fixed time (`3`). This value defaults to `false`.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'use_pmi'?: boolean;
    /**
     * Whether to enable the [**Waiting Room** feature](https://support.zoom.us/hc/en-us/articles/115000332726-Waiting-Room). If this value is `true`, this **disables** the `join_before_host` setting.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'waiting_room'?: boolean;
    /**
     * Whether to add a watermark when viewing a shared screen.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'watermark'?: boolean;
    /**
     * Whether the **Allow host to save video order** feature is enabled.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'host_save_video_order'?: boolean;
    /**
     * Whether the **Allow alternative hosts to add or edit polls** feature is enabled. This requires Zoom version 5.8.0 or higher.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'alternative_host_update_polls'?: boolean;
    /**
     * Whether to set the meeting as an internal meeting.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'internal_meeting'?: boolean;
    /**
     * 
     * @type {MeetingsCreateMeetingRequestSettingsContinuousMeetingChat}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'continuous_meeting_chat'?: MeetingsCreateMeetingRequestSettingsContinuousMeetingChat;
    /**
     * Whether to set the meeting as a participant focused meeting.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'participant_focused_meeting'?: boolean;
    /**
     * Whether to push meeting changes to the calendar.    To enable this feature, configure the **Configure Calendar and Contacts Service** in the user\'s profile page of the Zoom web portal and enable the **Automatically sync Zoom calendar events information bi-directionally between Zoom and integrated calendars.** setting in the **Settings** page of the Zoom web portal. * `true` - Push meeting changes to the calendar. * `false` - Do not push meeting changes to the calendar.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'push_change_to_calendar'?: boolean;
    /**
     * The meeting\'s resources.
     * @type {Array<MeetingsCreateMeetingRequestSettingsResourcesInner>}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'resources'?: Array<MeetingsCreateMeetingRequestSettingsResourcesInner>;
    /**
     * Whether to automatically start a meeting summary.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'auto_start_meeting_summary'?: boolean;
    /**
     * Whether to automatically start AI Companion questions.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettings
     */
    'auto_start_ai_companion_questions'?: boolean;
}

type MeetingsCreateMeetingRequestSettingsApprovalTypeEnum = 0 | 1 | 2
type MeetingsCreateMeetingRequestSettingsAudioEnum = 'both' | 'telephony' | 'voip' | 'thirdParty'
type MeetingsCreateMeetingRequestSettingsAutoRecordingEnum = 'local' | 'cloud' | 'none'
type MeetingsCreateMeetingRequestSettingsCalendarTypeEnum = 1 | 2
type MeetingsCreateMeetingRequestSettingsEncryptionTypeEnum = 'enhanced_encryption' | 'e2ee'
type MeetingsCreateMeetingRequestSettingsJbhTimeEnum = 0 | 5 | 10
type MeetingsCreateMeetingRequestSettingsRegistrationTypeEnum = 1 | 2 | 3


