/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsGetMeetingSurveyResponseCustomSurveyQuestionsInner } from './meetings-get-meeting-survey-response-custom-survey-questions-inner';

/**
 * Information about the customized meeting survey.
 * @export
 * @interface MeetingsGetMeetingSurveyResponseCustomSurvey
 */
export interface MeetingsGetMeetingSurveyResponseCustomSurvey {
    /**
     * The survey\'s title, up to 64 characters.
     * @type {string}
     * @memberof MeetingsGetMeetingSurveyResponseCustomSurvey
     */
    'title'?: string;
    /**
     * Allow participants to anonymously answer survey questions.    This value defaults to `true`.
     * @type {boolean}
     * @memberof MeetingsGetMeetingSurveyResponseCustomSurvey
     */
    'anonymous'?: boolean;
    /**
     * Whether to display the number in the question name.    This value defaults to `true`.
     * @type {boolean}
     * @memberof MeetingsGetMeetingSurveyResponseCustomSurvey
     */
    'numbered_questions'?: boolean;
    /**
     * Whether to display the question type in the question name.    This value defaults to `false`.
     * @type {boolean}
     * @memberof MeetingsGetMeetingSurveyResponseCustomSurvey
     */
    'show_question_type'?: boolean;
    /**
     * The survey\'s feedback, up to 320 characters.    This value defaults to `Thank you so much for taking the time to complete the survey. Your feedback really makes a difference.`.
     * @type {string}
     * @memberof MeetingsGetMeetingSurveyResponseCustomSurvey
     */
    'feedback'?: string;
    /**
     * Information about the meeting survey\'s questions.
     * @type {Array<MeetingsGetMeetingSurveyResponseCustomSurveyQuestionsInner>}
     * @memberof MeetingsGetMeetingSurveyResponseCustomSurvey
     */
    'questions'?: Array<MeetingsGetMeetingSurveyResponseCustomSurveyQuestionsInner>;
}

