/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MeetingsUpdateDetailsRequestSettingsAuthenticationExceptionInner
 */
export interface MeetingsUpdateDetailsRequestSettingsAuthenticationExceptionInner {
    /**
     * The participant\'s email address.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettingsAuthenticationExceptionInner
     */
    'email'?: string;
    /**
     * The participant\'s name.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettingsAuthenticationExceptionInner
     */
    'name'?: string;
    /**
     * URL for participants to join the meeting
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettingsAuthenticationExceptionInner
     */
    'join_url'?: string;
}

