/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsListMeetingTemplatesResponseTemplatesInner } from './meetings-list-meeting-templates-response-templates-inner';

/**
 * 
 * @export
 * @interface MeetingsListMeetingTemplatesResponse
 */
export interface MeetingsListMeetingTemplatesResponse {
    /**
     * 
     * @type {Array<MeetingsListMeetingTemplatesResponseTemplatesInner>}
     * @memberof MeetingsListMeetingTemplatesResponse
     */
    'templates'?: Array<MeetingsListMeetingTemplatesResponseTemplatesInner>;
    /**
     * Total records found for this request.
     * @type {number}
     * @memberof MeetingsListMeetingTemplatesResponse
     */
    'total_records'?: number;
}

