/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MeetingsListPastMeetingQaResponseQuestionsInnerQuestionDetailsInner
 */
export interface MeetingsListPastMeetingQaResponseQuestionsInnerQuestionDetailsInner {
    /**
     * An answer submitted for the question. The value is \'live answered\' if this is a live answer.
     * @type {string}
     * @memberof MeetingsListPastMeetingQaResponseQuestionsInnerQuestionDetailsInner
     */
    'answer'?: string;
    /**
     * A question asked during the Q&amp;A.
     * @type {string}
     * @memberof MeetingsListPastMeetingQaResponseQuestionsInnerQuestionDetailsInner
     */
    'question'?: string;
}

