/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsCreateBatchPollsRequestPollsInner } from './meetings-create-batch-polls-request-polls-inner';

/**
 * 
 * @export
 * @interface MeetingsCreateBatchPollsRequest
 */
export interface MeetingsCreateBatchPollsRequest {
    /**
     * Information about the meeting\'s polls.
     * @type {Array<MeetingsCreateBatchPollsRequestPollsInner>}
     * @memberof MeetingsCreateBatchPollsRequest
     */
    'polls'?: Array<MeetingsCreateBatchPollsRequestPollsInner>;
}

