/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsListPastMeetingQaResponseQuestionsInnerQuestionDetailsInner } from './meetings-list-past-meeting-qa-response-questions-inner-question-details-inner';

/**
 * 
 * @export
 * @interface MeetingsListPastMeetingQaResponseQuestionsInner
 */
export interface MeetingsListPastMeetingQaResponseQuestionsInner {
    /**
     * The user\'s email address. If the user is **not** part of the host\'s account, this returns an empty string value, with some exceptions. See [Email address display rules](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#email-address-display-rules) for details.
     * @type {string}
     * @memberof MeetingsListPastMeetingQaResponseQuestionsInner
     */
    'email'?: string;
    /**
     * The user\'s name. If `anonymous` option is enabled for the Q&amp;A, the participant\'s information is be kept anonymous and the value of `name` field is `Anonymous Attendee`.
     * @type {string}
     * @memberof MeetingsListPastMeetingQaResponseQuestionsInner
     */
    'name'?: string;
    /**
     * 
     * @type {Array<MeetingsListPastMeetingQaResponseQuestionsInnerQuestionDetailsInner>}
     * @memberof MeetingsListPastMeetingQaResponseQuestionsInner
     */
    'question_details'?: Array<MeetingsListPastMeetingQaResponseQuestionsInnerQuestionDetailsInner>;
}

