/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsGetMeetingSummaryResponseEditedSummary } from './meetings-get-meeting-summary-response-edited-summary';
import { MeetingsGetMeetingSummaryResponseSummaryDetailsInner } from './meetings-get-meeting-summary-response-summary-details-inner';

/**
 * 
 * @export
 * @interface MeetingsGetMeetingSummaryResponse
 */
export interface MeetingsGetMeetingSummaryResponse {
    /**
     * The ID of the user who is set as the meeting host.
     * @type {string}
     * @memberof MeetingsGetMeetingSummaryResponse
     */
    'meeting_host_id'?: string;
    /**
     * The meeting host\'s email address.
     * @type {string}
     * @memberof MeetingsGetMeetingSummaryResponse
     */
    'meeting_host_email'?: string;
    /**
     * The unique meeting ID.   Each meeting instance generates its own meeting UUID. After a meeting ends, a new UUID is generated for the next instance of the meeting.   Use the [**List past meeting instances**](https://developers.zoom.us) API to retrieve a list of UUIDs from past meeting instances. [Double encode](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#meeting-id-and-uuid) your UUID when using it for API calls if the UUID begins with a `/` or contains `//` in it. 
     * @type {string}
     * @memberof MeetingsGetMeetingSummaryResponse
     */
    'meeting_uuid'?: string;
    /**
     * [The meeting ID](https://support.zoom.us/hc/en-us/articles/201362373-What-is-a-Meeting-ID-)  The meeting\'s unique identifier in **long** format, represented as int64 data type in JSON. Also known as the meeting number.
     * @type {number}
     * @memberof MeetingsGetMeetingSummaryResponse
     */
    'meeting_id'?: number;
    /**
     * The meeting topic.
     * @type {string}
     * @memberof MeetingsGetMeetingSummaryResponse
     */
    'meeting_topic'?: string;
    /**
     * The meeting\'s start date and time.
     * @type {string}
     * @memberof MeetingsGetMeetingSummaryResponse
     */
    'meeting_start_time'?: string;
    /**
     * The meeting\'s end date and time.
     * @type {string}
     * @memberof MeetingsGetMeetingSummaryResponse
     */
    'meeting_end_time'?: string;
    /**
     * The summary\'s start date and time.
     * @type {string}
     * @memberof MeetingsGetMeetingSummaryResponse
     */
    'summary_start_time'?: string;
    /**
     * The summary\'s end date and time.
     * @type {string}
     * @memberof MeetingsGetMeetingSummaryResponse
     */
    'summary_end_time'?: string;
    /**
     * The date and time when the meeting summary was created.
     * @type {string}
     * @memberof MeetingsGetMeetingSummaryResponse
     */
    'summary_created_time'?: string;
    /**
     * The date and time when the meeting summary was last modified.
     * @type {string}
     * @memberof MeetingsGetMeetingSummaryResponse
     */
    'summary_last_modified_time'?: string;
    /**
     * The summary title.
     * @type {string}
     * @memberof MeetingsGetMeetingSummaryResponse
     */
    'summary_title'?: string;
    /**
     * The summary overview.
     * @type {string}
     * @memberof MeetingsGetMeetingSummaryResponse
     */
    'summary_overview'?: string;
    /**
     * The summary content details.
     * @type {Array<MeetingsGetMeetingSummaryResponseSummaryDetailsInner>}
     * @memberof MeetingsGetMeetingSummaryResponse
     */
    'summary_details'?: Array<MeetingsGetMeetingSummaryResponseSummaryDetailsInner>;
    /**
     * The next steps.
     * @type {Array<string>}
     * @memberof MeetingsGetMeetingSummaryResponse
     */
    'next_steps'?: Array<string>;
    /**
     * 
     * @type {MeetingsGetMeetingSummaryResponseEditedSummary}
     * @memberof MeetingsGetMeetingSummaryResponse
     */
    'edited_summary'?: MeetingsGetMeetingSummaryResponseEditedSummary;
}

