/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MeetingsUpdateDetailsRequestSettingsGlobalDialInNumbersInner
 */
export interface MeetingsUpdateDetailsRequestSettingsGlobalDialInNumbersInner {
    /**
     * City of the number, if any, such as Chicago.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettingsGlobalDialInNumbersInner
     */
    'city'?: string;
    /**
     * Country code, such as BR.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettingsGlobalDialInNumbersInner
     */
    'country'?: string;
    /**
     * Full name of country, such as Brazil.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettingsGlobalDialInNumbersInner
     */
    'country_name'?: string;
    /**
     * Phone number, such as +1 2332357613.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettingsGlobalDialInNumbersInner
     */
    'number'?: string;
    /**
     * Type of number. 
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettingsGlobalDialInNumbersInner
     */
    'type'?: MeetingsUpdateDetailsRequestSettingsGlobalDialInNumbersInnerTypeEnum;
}

type MeetingsUpdateDetailsRequestSettingsGlobalDialInNumbersInnerTypeEnum = 'toll' | 'tollfree'


