/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsCreateMeetingResponseSettingsApprovedOrDeniedCountriesOrRegions } from './meetings-create-meeting-response-settings-approved-or-denied-countries-or-regions';
import { MeetingsCreateMeetingResponseSettingsAuthenticationExceptionInner } from './meetings-create-meeting-response-settings-authentication-exception-inner';
import { MeetingsCreateMeetingResponseSettingsBreakoutRoom } from './meetings-create-meeting-response-settings-breakout-room';
import { MeetingsCreateMeetingResponseSettingsContinuousMeetingChat } from './meetings-create-meeting-response-settings-continuous-meeting-chat';
import { MeetingsCreateMeetingResponseSettingsCustomKeysInner } from './meetings-create-meeting-response-settings-custom-keys-inner';
import { MeetingsCreateMeetingResponseSettingsGlobalDialInNumbersInner } from './meetings-create-meeting-response-settings-global-dial-in-numbers-inner';
import { MeetingsCreateMeetingResponseSettingsLanguageInterpretation } from './meetings-create-meeting-response-settings-language-interpretation';
import { MeetingsCreateMeetingResponseSettingsResourcesInner } from './meetings-create-meeting-response-settings-resources-inner';
import { MeetingsCreateMeetingResponseSettingsSignLanguageInterpretation } from './meetings-create-meeting-response-settings-sign-language-interpretation';

/**
 * Meeting settings.
 * @export
 * @interface MeetingsCreateMeetingResponseSettings
 */
export interface MeetingsCreateMeetingResponseSettings {
    /**
     * Allow attendees to join the meeting from multiple devices. This setting only works for meetings that require [registration](https://support.zoom.us/hc/en-us/articles/211579443-Setting-up-registration-for-a-meeting).
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'allow_multiple_devices'?: boolean;
    /**
     * A semicolon-separated list of the meeting\'s alternative hosts\' email addresses or IDs.
     * @type {string}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'alternative_hosts'?: string;
    /**
     * Flag to determine whether to send email notifications to alternative hosts, default value is true.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'alternative_hosts_email_notification'?: boolean;
    /**
     * Whether the **Allow alternative hosts to add or edit polls** feature is enabled. This requires Zoom version 5.8.0 or higher.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'alternative_host_update_polls'?: boolean;
    /**
     * Enable registration and set approval for the registration. Note that this feature requires the host to be of **Licensed** user type. **Registration cannot be enabled for a basic user.**            `0` - Automatically approve.    `1` - Manually approve.    `2` - No registration required.
     * @type {number}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'approval_type'?: MeetingsCreateMeetingResponseSettingsApprovalTypeEnum;
    /**
     * 
     * @type {MeetingsCreateMeetingResponseSettingsApprovedOrDeniedCountriesOrRegions}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'approved_or_denied_countries_or_regions'?: MeetingsCreateMeetingResponseSettingsApprovedOrDeniedCountriesOrRegions;
    /**
     * Determine how participants can join the audio portion of the meeting.    `both` - Both Telephony and VoIP.    `telephony` - Telephony only.    `voip` - VoIP only.    `thirdParty` - Third party audio conference.
     * @type {string}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'audio'?: MeetingsCreateMeetingResponseSettingsAudioEnum;
    /**
     * Third party audio conference info.
     * @type {string}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'audio_conference_info'?: string;
    /**
     * If user has configured [Sign Into Zoom with Specified Domains](https://support.zoom.us/hc/en-us/articles/360037117472-Authentication-Profiles-for-Meetings-and-Webinars#h_5c0df2e1-cfd2-469f-bb4a-c77d7c0cca6f) option, this will list the domains that are authenticated.
     * @type {string}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'authentication_domains'?: string;
    /**
     * The participants added here will receive unique meeting invite links and bypass authentication.
     * @type {Array<MeetingsCreateMeetingResponseSettingsAuthenticationExceptionInner>}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'authentication_exception'?: Array<MeetingsCreateMeetingResponseSettingsAuthenticationExceptionInner>;
    /**
     * Authentication name set in the [authentication profile](https://support.zoom.us/hc/en-us/articles/360037117472-Authentication-Profiles-for-Meetings-and-Webinars#h_5c0df2e1-cfd2-469f-bb4a-c77d7c0cca6f).
     * @type {string}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'authentication_name'?: string;
    /**
     * Meeting authentication option ID.
     * @type {string}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'authentication_option'?: string;
    /**
     * Automatic recording.  `local` - Record on local.    `cloud` -  Record on cloud.    `none` - Disabled.
     * @type {string}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'auto_recording'?: MeetingsCreateMeetingResponseSettingsAutoRecordingEnum;
    /**
     * 
     * @type {MeetingsCreateMeetingResponseSettingsBreakoutRoom}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'breakout_room'?: MeetingsCreateMeetingResponseSettingsBreakoutRoom;
    /**
     * The type of calendar integration used to schedule the meeting.  * `1` - [Zoom Outlook add-in](https://support.zoom.us/hc/en-us/articles/360031592971-Getting-started-with-Outlook-plugin-and-add-in)  * `2` - [Zoom for Google Workspace add-on](https://support.zoom.us/hc/en-us/articles/360020187492-Using-the-Zoom-for-Google-Workspace-add-on)  Works with the `private_meeting` field to determine whether to share details of meetings or not.
     * @type {number}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'calendar_type'?: MeetingsCreateMeetingResponseSettingsCalendarTypeEnum;
    /**
     * Close registration after event date.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'close_registration'?: boolean;
    /**
     * Host meeting in China.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     * @deprecated
     */
    'cn_meeting'?: boolean;
    /**
     * Contact email for registration
     * @type {string}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'contact_email'?: string;
    /**
     * Contact name for registration
     * @type {string}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'contact_name'?: string;
    /**
     * Custom keys and values assigned to the meeting.
     * @type {Array<MeetingsCreateMeetingResponseSettingsCustomKeysInner>}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'custom_keys'?: Array<MeetingsCreateMeetingResponseSettingsCustomKeysInner>;
    /**
     * Whether to send email notifications to [alternative hosts](https://support.zoom.us/hc/en-us/articles/208220166) and [users with scheduling privileges](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-privilege). This value defaults to `true`.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'email_notification'?: boolean;
    /**
     * Choose between enhanced encryption and [end-to-end encryption](https://support.zoom.us/hc/en-us/articles/360048660871) when starting or a meeting. When using end-to-end encryption, several features (e.g. cloud recording, phone/SIP/H.323 dial-in) will be **automatically disabled**.   `enhanced_encryption` - Enhanced encryption. Encryption is stored in the cloud if you enable this option.       `e2ee` - [End-to-end encryption](https://support.zoom.us/hc/en-us/articles/360048660871). The encryption key is stored in your local device and can not be obtained by anyone else. Enabling this setting also **disables** the join before host, cloud recording, streaming, live transcription, breakout rooms, polling, 1:1 private chat, and meeting reactions features.
     * @type {string}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'encryption_type'?: MeetingsCreateMeetingResponseSettingsEncryptionTypeEnum;
    /**
     * Only signed in users can join this meeting.  **This field is deprecated and will not be supported in the future.**          As an alternative, use the `meeting_authentication`, `authentication_option`, and `authentication_domains` fields to understand the [authentication configurations](https://support.zoom.us/hc/en-us/articles/360037117472-Authentication-Profiles-for-Meetings-and-Webinars) set for the meeting.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     * @deprecated
     */
    'enforce_login'?: boolean;
    /**
     * Only signed in users with specified domains can join meetings.  **This field is deprecated and will not be supported in the future.**          As an alternative, use the `meeting_authentication`, `authentication_option`, and `authentication_domains` fields to understand the [authentication configurations](https://support.zoom.us/hc/en-us/articles/360037117472-Authentication-Profiles-for-Meetings-and-Webinars) set for the meeting.
     * @type {string}
     * @memberof MeetingsCreateMeetingResponseSettings
     * @deprecated
     */
    'enforce_login_domains'?: string;
    /**
     * Whether the [**Focus Mode** feature](https://support.zoom.us/hc/en-us/articles/360061113751-Using-focus-mode) is enabled when the meeting starts.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'focus_mode'?: boolean;
    /**
     * List of global dial-in countries.
     * @type {Array<string>}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'global_dial_in_countries'?: Array<string>;
    /**
     * Global dial-in countries or regions.
     * @type {Array<MeetingsCreateMeetingResponseSettingsGlobalDialInNumbersInner>}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'global_dial_in_numbers'?: Array<MeetingsCreateMeetingResponseSettingsGlobalDialInNumbersInner>;
    /**
     * Start video when the host joins the meeting.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'host_video'?: boolean;
    /**
     * Host meeting in India.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     * @deprecated
     */
    'in_meeting'?: boolean;
    /**
     * If the value of `join_before_host` field is set to `true`, use this field to indicate time limits when a participant may join a meeting before a host.  *  `0` - Allow participant to join anytime. *  `5`- Allow participant to join 5 minutes before meeting start time.  * `10` - Allow participant to join 10 minutes before meeting start time.
     * @type {number}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'jbh_time'?: MeetingsCreateMeetingResponseSettingsJbhTimeEnum;
    /**
     * Allow participants to join the meeting before the host starts the meeting. Only used for scheduled or recurring meetings.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'join_before_host'?: boolean;
    /**
     * 
     * @type {MeetingsCreateMeetingResponseSettingsLanguageInterpretation}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'language_interpretation'?: MeetingsCreateMeetingResponseSettingsLanguageInterpretation;
    /**
     * 
     * @type {MeetingsCreateMeetingResponseSettingsSignLanguageInterpretation}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'sign_language_interpretation'?: MeetingsCreateMeetingResponseSettingsSignLanguageInterpretation;
    /**
     * `true` - Only authenticated users can join meetings.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'meeting_authentication'?: boolean;
    /**
     * Mute participants upon entry.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'mute_upon_entry'?: boolean;
    /**
     * Start video when participants join the meeting.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'participant_video'?: boolean;
    /**
     * Whether the meeting is set as private.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'private_meeting'?: boolean;
    /**
     * Whether to send registrants an email confirmation. * `true` - Send a confirmation email. * `false` - Do not send a confirmation email.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'registrants_confirmation_email'?: boolean;
    /**
     * Whether to send registrants email notifications about their registration approval, cancellation, or rejection.  * `true` - Send an email notification. * `false` - Do not send an email notification.   Set this value to `true` to also use the `registrants_confirmation_email` parameter.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'registrants_email_notification'?: boolean;
    /**
     * Registration type. Used for recurring meeting with fixed time only.   `1` - Attendees register once and can attend any of the occurrences.    `2` - Attendees need to register for each occurrence to attend.    `3` - Attendees register once and can choose one or more occurrences to attend.
     * @type {number}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'registration_type'?: MeetingsCreateMeetingResponseSettingsRegistrationTypeEnum;
    /**
     * Show social share buttons on the meeting registration page. This setting only works for meetings that require [registration](https://support.zoom.us/hc/en-us/articles/211579443-Setting-up-registration-for-a-meeting).
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'show_share_button'?: boolean;
    /**
     * Use a [personal meeting ID (PMI)](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#understanding-personal-meeting-id-pmi). Only used for scheduled meetings and recurring meetings with no fixed time.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'use_pmi'?: boolean;
    /**
     * Enable the waiting room.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'waiting_room'?: boolean;
    /**
     * Add a watermark when viewing a shared screen.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'watermark'?: boolean;
    /**
     * Whether the **Allow host to save video order** feature is enabled.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'host_save_video_order'?: boolean;
    /**
     * Whether to set the meeting as an internal meeting.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'internal_meeting'?: boolean;
    /**
     * 
     * @type {MeetingsCreateMeetingResponseSettingsContinuousMeetingChat}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'continuous_meeting_chat'?: MeetingsCreateMeetingResponseSettingsContinuousMeetingChat;
    /**
     * Whether to set the meeting as a participant focused meeting.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'participant_focused_meeting'?: boolean;
    /**
     * Whether to push meeting changes to the calendar.    To enable this feature, configure the **Configure Calendar and Contacts Service** in the user\'s profile page of the Zoom web portal and enable the **Automatically sync Zoom calendar events information bi-directionally between Zoom and integrated calendars.** setting in the **Settings** page of the Zoom web portal. * `true` - Push meeting changes to the calendar. * `false` - Do not push meeting changes to the calendar.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'push_change_to_calendar'?: boolean;
    /**
     * The meeting\'s resources.
     * @type {Array<MeetingsCreateMeetingResponseSettingsResourcesInner>}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'resources'?: Array<MeetingsCreateMeetingResponseSettingsResourcesInner>;
    /**
     * Whether to automatically start a meeting summary.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'auto_start_meeting_summary'?: boolean;
    /**
     * Whether to automatically start AI Companion questions.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingResponseSettings
     */
    'auto_start_ai_companion_questions'?: boolean;
}

type MeetingsCreateMeetingResponseSettingsApprovalTypeEnum = 0 | 1 | 2
type MeetingsCreateMeetingResponseSettingsAudioEnum = 'both' | 'telephony' | 'voip' | 'thirdParty'
type MeetingsCreateMeetingResponseSettingsAutoRecordingEnum = 'local' | 'cloud' | 'none'
type MeetingsCreateMeetingResponseSettingsCalendarTypeEnum = 1 | 2
type MeetingsCreateMeetingResponseSettingsEncryptionTypeEnum = 'enhanced_encryption' | 'e2ee'
type MeetingsCreateMeetingResponseSettingsJbhTimeEnum = 0 | 5 | 10
type MeetingsCreateMeetingResponseSettingsRegistrationTypeEnum = 1 | 2 | 3


