/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Meeting invitation details.
 * @export
 * @interface MeetingsGetInvitationNoteResponse
 */
export interface MeetingsGetInvitationNoteResponse {
    /**
     * Meeting invitation.
     * @type {string}
     * @memberof MeetingsGetInvitationNoteResponse
     */
    'invitation'?: string;
    /**
     * A list of SIP phone addresses.
     * @type {Array<string>}
     * @memberof MeetingsGetInvitationNoteResponse
     */
    'sip_links'?: Array<string>;
}

