/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsUpdateDetailsRequestSettingsBreakoutRoomRoomsInner } from './meetings-update-details-request-settings-breakout-room-rooms-inner';

/**
 * Setting to [pre-assign breakout rooms](https://support.zoom.us/hc/en-us/articles/360032752671-Pre-assigning-participants-to-breakout-rooms#h_36f71353-4190-48a2-b999-ca129861c1f4).
 * @export
 * @interface MeetingsUpdateDetailsRequestSettingsBreakoutRoom
 */
export interface MeetingsUpdateDetailsRequestSettingsBreakoutRoom {
    /**
     * Set this field\'s value to `true` to enable the [breakout room pre-assign](https://support.zoom.us/hc/en-us/articles/360032752671-Pre-assigning-participants-to-breakout-rooms#h_36f71353-4190-48a2-b999-ca129861c1f4) option.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettingsBreakoutRoom
     */
    'enable'?: boolean;
    /**
     * Create room(s).
     * @type {Array<MeetingsUpdateDetailsRequestSettingsBreakoutRoomRoomsInner>}
     * @memberof MeetingsUpdateDetailsRequestSettingsBreakoutRoom
     */
    'rooms'?: Array<MeetingsUpdateDetailsRequestSettingsBreakoutRoomRoomsInner>;
}

