/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Approve or block users from specific regions or countries from joining this meeting.  
 * @export
 * @interface MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegions
 */
export interface MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegions {
    /**
     * List of countries or regions from where participants can join this meeting. 
     * @type {Array<string>}
     * @memberof MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegions
     */
    'approved_list'?: Array<string>;
    /**
     * List of countries or regions from where participants can not join this meeting. 
     * @type {Array<string>}
     * @memberof MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegions
     */
    'denied_list'?: Array<string>;
    /**
     * `true` - Setting enabled to either allow users or block users from specific regions to join your meetings.    `false` - Setting disabled.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegions
     */
    'enable'?: boolean;
    /**
     * Specify whether to allow users from specific regions to join this meeting, or block users from specific regions from joining this meeting.    `approve` - Allow users from specific regions or countries to join this meeting. If this setting is selected, include the approved regions or countries in the `approved_list`.     `deny` - Block users from specific regions or countries from joining this meeting. If this setting is selected, include the approved regions orcountries in the `denied_list`
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegions
     */
    'method'?: MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegionsMethodEnum;
}

type MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegionsMethodEnum = 'approve' | 'deny'


