/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsCreateBatchPollsResponsePollsInner } from './meetings-create-batch-polls-response-polls-inner';

/**
 * 
 * @export
 * @interface MeetingsCreateBatchPollsResponse
 */
export interface MeetingsCreateBatchPollsResponse {
    /**
     * 
     * @type {Array<MeetingsCreateBatchPollsResponsePollsInner>}
     * @memberof MeetingsCreateBatchPollsResponse
     */
    'polls'?: Array<MeetingsCreateBatchPollsResponsePollsInner>;
}

