/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingAndWebinarPollingObject } from './meeting-and-webinar-polling-object';

/**
 * Poll List
 * @export
 * @interface MeetingsListMeetingPollsResponse
 */
export interface MeetingsListMeetingPollsResponse {
    /**
     * Array of Polls
     * @type {Array<MeetingAndWebinarPollingObject>}
     * @memberof MeetingsListMeetingPollsResponse
     */
    'polls'?: Array<MeetingAndWebinarPollingObject>;
    /**
     * The number of all records available across pages
     * @type {number}
     * @memberof MeetingsListMeetingPollsResponse
     */
    'total_records'?: number;
}

