/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsListPastMeetingInstancesResponseMeetingsInner } from './meetings-list-past-meeting-instances-response-meetings-inner';

/**
 * List of Meetings
 * @export
 * @interface MeetingsListPastMeetingInstancesResponse
 */
export interface MeetingsListPastMeetingInstancesResponse {
    /**
     * List of ended meeting instances.
     * @type {Array<MeetingsListPastMeetingInstancesResponseMeetingsInner>}
     * @memberof MeetingsListPastMeetingInstancesResponse
     */
    'meetings'?: Array<MeetingsListPastMeetingInstancesResponseMeetingsInner>;
}

