/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegions } from './meetings-update-details-request-settings-approved-or-denied-countries-or-regions';
import { MeetingsUpdateDetailsRequestSettingsAuthenticationExceptionInner } from './meetings-update-details-request-settings-authentication-exception-inner';
import { MeetingsUpdateDetailsRequestSettingsBreakoutRoom } from './meetings-update-details-request-settings-breakout-room';
import { MeetingsUpdateDetailsRequestSettingsContinuousMeetingChat } from './meetings-update-details-request-settings-continuous-meeting-chat';
import { MeetingsUpdateDetailsRequestSettingsCustomKeysInner } from './meetings-update-details-request-settings-custom-keys-inner';
import { MeetingsUpdateDetailsRequestSettingsGlobalDialInNumbersInner } from './meetings-update-details-request-settings-global-dial-in-numbers-inner';
import { MeetingsUpdateDetailsRequestSettingsLanguageInterpretation } from './meetings-update-details-request-settings-language-interpretation';
import { MeetingsUpdateDetailsRequestSettingsMeetingInviteesInner } from './meetings-update-details-request-settings-meeting-invitees-inner';
import { MeetingsUpdateDetailsRequestSettingsResourcesInner } from './meetings-update-details-request-settings-resources-inner';
import { MeetingsUpdateDetailsRequestSettingsSignLanguageInterpretation } from './meetings-update-details-request-settings-sign-language-interpretation';

/**
 * Meeting settings.
 * @export
 * @interface MeetingsUpdateDetailsRequestSettings
 */
export interface MeetingsUpdateDetailsRequestSettings {
    /**
     * Allow attendees to join the meeting from multiple devices. This setting only works for meetings that require [registration](https://support.zoom.us/hc/en-us/articles/211579443-Setting-up-registration-for-a-meeting).
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'allow_multiple_devices'?: boolean;
    /**
     * A semicolon-separated list of the meeting\'s alternative hosts\' email addresses or IDs.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'alternative_hosts'?: string;
    /**
     * Flag to determine whether to send email notifications to alternative hosts, default value is true.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'alternative_hosts_email_notification'?: boolean;
    /**
     * Whether the **Allow alternative hosts to add or edit polls** feature is enabled. This requires Zoom version 5.8.0 or higher.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'alternative_host_update_polls'?: boolean;
    /**
     * Enable registration and set approval for the registration. Note that this feature requires the host to be of **Licensed** user type. **Registration cannot be enabled for a basic user.**            `0` - Automatically approve.    `1` - Manually approve.    `2` - No registration required.
     * @type {number}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'approval_type'?: MeetingsUpdateDetailsRequestSettingsApprovalTypeEnum;
    /**
     * 
     * @type {MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegions}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'approved_or_denied_countries_or_regions'?: MeetingsUpdateDetailsRequestSettingsApprovedOrDeniedCountriesOrRegions;
    /**
     * Determine how participants can join the audio portion of the meeting.    `both` - Both Telephony and VoIP.    `telephony` - Telephony only.    `voip` - VoIP only.    `thirdParty` - Third party audio conference.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'audio'?: MeetingsUpdateDetailsRequestSettingsAudioEnum;
    /**
     * Third party audio conference info.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'audio_conference_info'?: string;
    /**
     * If user has configured [Sign Into Zoom with Specified Domains](https://support.zoom.us/hc/en-us/articles/360037117472-Authentication-Profiles-for-Meetings-and-Webinars#h_5c0df2e1-cfd2-469f-bb4a-c77d7c0cca6f) option, this will list the domains that are authenticated.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'authentication_domains'?: string;
    /**
     * The participants added here will receive unique meeting invite links and bypass authentication.
     * @type {Array<MeetingsUpdateDetailsRequestSettingsAuthenticationExceptionInner>}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'authentication_exception'?: Array<MeetingsUpdateDetailsRequestSettingsAuthenticationExceptionInner>;
    /**
     * Authentication name set in the [authentication profile](https://support.zoom.us/hc/en-us/articles/360037117472-Authentication-Profiles-for-Meetings-and-Webinars#h_5c0df2e1-cfd2-469f-bb4a-c77d7c0cca6f).
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'authentication_name'?: string;
    /**
     * Meeting authentication option ID.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'authentication_option'?: string;
    /**
     * Automatic recording.   `local` - Record on local.    `cloud` -  Record on cloud.    `none` - Disabled.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'auto_recording'?: MeetingsUpdateDetailsRequestSettingsAutoRecordingEnum;
    /**
     * 
     * @type {MeetingsUpdateDetailsRequestSettingsBreakoutRoom}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'breakout_room'?: MeetingsUpdateDetailsRequestSettingsBreakoutRoom;
    /**
     * The type of calendar integration used to schedule the meeting.  * `1` - [Zoom Outlook add-in](https://support.zoom.us/hc/en-us/articles/360031592971-Getting-started-with-Outlook-plugin-and-add-in)  * `2` - [Zoom for Google Workspace add-on](https://support.zoom.us/hc/en-us/articles/360020187492-Using-the-Zoom-for-Google-Workspace-add-on)  Works with the `private_meeting` field to determine whether to share details of meetings.
     * @type {number}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'calendar_type'?: MeetingsUpdateDetailsRequestSettingsCalendarTypeEnum;
    /**
     * Close registration after the event date.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'close_registration'?: boolean;
    /**
     * Host the meeting in China.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     * @deprecated
     */
    'cn_meeting'?: boolean;
    /**
     * Contact email for registration.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'contact_email'?: string;
    /**
     * Contact name for registration.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'contact_name'?: string;
    /**
     * Custom keys and values assigned to the meeting.
     * @type {Array<MeetingsUpdateDetailsRequestSettingsCustomKeysInner>}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'custom_keys'?: Array<MeetingsUpdateDetailsRequestSettingsCustomKeysInner>;
    /**
     * Whether to send email notifications to [alternative hosts](https://support.zoom.us/hc/en-us/articles/208220166) and [users with scheduling privileges](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-privilege). This value defaults to `true`.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'email_notification'?: boolean;
    /**
     * Choose between enhanced encryption and [end-to-end encryption](https://support.zoom.us/hc/en-us/articles/360048660871) when starting or a meeting. When using end-to-end encryption, several features such cloud recording and phone/SIP/H.323 dial-in, will be **automatically disabled**.     `enhanced_encryption` - Enhanced encryption. Encryption is stored in the cloud if you enable this option.       `e2ee` - [End-to-end encryption](https://support.zoom.us/hc/en-us/articles/360048660871). The encryption key is stored in your local device and can not be obtained by anyone else. Enabling this setting also **disables** the features join before host, cloud recording, streaming, live transcription, breakout rooms, polling, 1:1 private chat, and meeting reactions.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'encryption_type'?: MeetingsUpdateDetailsRequestSettingsEncryptionTypeEnum;
    /**
     * Only signed in users can join this meeting.  **This field is deprecated and will not be supported in the future.**          As an alternative, use the `meeting_authentication`, `authentication_option`, and `authentication_domains` fields to understand the [authentication configurations](https://support.zoom.us/hc/en-us/articles/360037117472-Authentication-Profiles-for-Meetings-and-Webinars) set for the meeting.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     * @deprecated
     */
    'enforce_login'?: boolean;
    /**
     * Only signed in users with specified domains can join meetings.  **This field is deprecated and will not be supported in the future.**          As an alternative, use the `meeting_authentication`, `authentication_option`. and `authentication_domains` fields to understand the [authentication configurations](https://support.zoom.us/hc/en-us/articles/360037117472-Authentication-Profiles-for-Meetings-and-Webinars) set for the meeting.
     * @type {string}
     * @memberof MeetingsUpdateDetailsRequestSettings
     * @deprecated
     */
    'enforce_login_domains'?: string;
    /**
     * Whether the [**Focus Mode** feature](https://support.zoom.us/hc/en-us/articles/360061113751-Using-focus-mode) is enabled when the meeting starts.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'focus_mode'?: boolean;
    /**
     * List of global dial-in countries
     * @type {Array<string>}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'global_dial_in_countries'?: Array<string>;
    /**
     * Global dial-in countries or regions
     * @type {Array<MeetingsUpdateDetailsRequestSettingsGlobalDialInNumbersInner>}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'global_dial_in_numbers'?: Array<MeetingsUpdateDetailsRequestSettingsGlobalDialInNumbersInner>;
    /**
     * Start video when the host joins the meeting.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'host_video'?: boolean;
    /**
     * Host meeting in India.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     * @deprecated
     */
    'in_meeting'?: boolean;
    /**
     * If the value of `join_before_host` field is set to true, use this field to indicate time limits for a participant to join a meeting before a host.  *  `0` - Allow participant to join anytime. *  `5` - Allow participant to join 5 minutes before meeting start time.  * `10` - Allow participant to join 10 minutes before meeting start time.
     * @type {number}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'jbh_time'?: MeetingsUpdateDetailsRequestSettingsJbhTimeEnum;
    /**
     * Allow participants to join the meeting before the host starts the meeting. Only used for scheduled or recurring meetings.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'join_before_host'?: boolean;
    /**
     * 
     * @type {MeetingsUpdateDetailsRequestSettingsLanguageInterpretation}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'language_interpretation'?: MeetingsUpdateDetailsRequestSettingsLanguageInterpretation;
    /**
     * 
     * @type {MeetingsUpdateDetailsRequestSettingsSignLanguageInterpretation}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'sign_language_interpretation'?: MeetingsUpdateDetailsRequestSettingsSignLanguageInterpretation;
    /**
     * `true`- Only authenticated users can join meetings.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'meeting_authentication'?: boolean;
    /**
     * A list of the meeting\'s invitees.
     * @type {Array<MeetingsUpdateDetailsRequestSettingsMeetingInviteesInner>}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'meeting_invitees'?: Array<MeetingsUpdateDetailsRequestSettingsMeetingInviteesInner>;
    /**
     * Mute participants upon entry.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'mute_upon_entry'?: boolean;
    /**
     * Start video when participants join the meeting.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'participant_video'?: boolean;
    /**
     * Whether the meeting is set as private.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'private_meeting'?: boolean;
    /**
     * Whether to send registrants an email confirmation. * `true` - Send a confirmation email. * `false` - Do not send a confirmation email.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'registrants_confirmation_email'?: boolean;
    /**
     * Whether to send registrants email notifications about their registration approval, cancellation, or rejection.  * `true` - Send an email notification. * `false` - Do not send an email notification.   Set this value to `true` to also use the `registrants_confirmation_email` parameter.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'registrants_email_notification'?: boolean;
    /**
     * Registration type. Used for recurring meeting with fixed time only.  `1` - Attendees register once and can attend any of the occurrences.    `2` - Attendees need to register for each occurrence to attend.    `3` - Attendees register once and can choose one or more occurrences to attend.
     * @type {number}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'registration_type'?: MeetingsUpdateDetailsRequestSettingsRegistrationTypeEnum;
    /**
     * Show social share buttons on the meeting registration page. This setting only works for meetings that require [registration](https://support.zoom.us/hc/en-us/articles/211579443-Setting-up-registration-for-a-meeting).
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'show_share_button'?: boolean;
    /**
     * Use a [personal meeting ID (PMI)](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#understanding-personal-meeting-id-pmi). Only used for scheduled meetings and recurring meetings with no fixed time.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'use_pmi'?: boolean;
    /**
     * Enable waiting room.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'waiting_room'?: boolean;
    /**
     * Add a watermark when viewing a shared screen.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'watermark'?: boolean;
    /**
     * Whether the **Allow host to save video order** feature is enabled.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'host_save_video_order'?: boolean;
    /**
     * Whether to set the meeting as an internal meeting.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'internal_meeting'?: boolean;
    /**
     * 
     * @type {MeetingsUpdateDetailsRequestSettingsContinuousMeetingChat}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'continuous_meeting_chat'?: MeetingsUpdateDetailsRequestSettingsContinuousMeetingChat;
    /**
     * Whether to set the meeting as a participant focused meeting.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'participant_focused_meeting'?: boolean;
    /**
     * The meeting\'s resources.
     * @type {Array<MeetingsUpdateDetailsRequestSettingsResourcesInner>}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'resources'?: Array<MeetingsUpdateDetailsRequestSettingsResourcesInner>;
    /**
     * Whether to automatically start meeting summary.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'auto_start_meeting_summary'?: boolean;
    /**
     * Whether to automatically start AI Companion questions.
     * @type {boolean}
     * @memberof MeetingsUpdateDetailsRequestSettings
     */
    'auto_start_ai_companion_questions'?: boolean;
}

type MeetingsUpdateDetailsRequestSettingsApprovalTypeEnum = 0 | 1 | 2
type MeetingsUpdateDetailsRequestSettingsAudioEnum = 'both' | 'telephony' | 'voip' | 'thirdParty'
type MeetingsUpdateDetailsRequestSettingsAutoRecordingEnum = 'local' | 'cloud' | 'none'
type MeetingsUpdateDetailsRequestSettingsCalendarTypeEnum = 1 | 2
type MeetingsUpdateDetailsRequestSettingsEncryptionTypeEnum = 'enhanced_encryption' | 'e2ee'
type MeetingsUpdateDetailsRequestSettingsJbhTimeEnum = 0 | 5 | 10
type MeetingsUpdateDetailsRequestSettingsRegistrationTypeEnum = 1 | 2 | 3


