/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MeetingsCreateInviteLinksResponseAttendeesInner
 */
export interface MeetingsCreateInviteLinksResponseAttendeesInner {
    /**
     * The URL to join the meeting.
     * @type {string}
     * @memberof MeetingsCreateInviteLinksResponseAttendeesInner
     */
    'join_url'?: string;
    /**
     * The user\'s display name.
     * @type {string}
     * @memberof MeetingsCreateInviteLinksResponseAttendeesInner
     */
    'name'?: string;
}

