/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsListRegistrantsResponseRegistrantsInnerCustomQuestionsInner } from './meetings-list-registrants-response-registrants-inner-custom-questions-inner';

/**
 *  Registrant.
 * @export
 * @interface MeetingsListRegistrantsResponseRegistrantsInner
 */
export interface MeetingsListRegistrantsResponseRegistrantsInner {
    /**
     * Registrant ID.
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'id'?: string;
    /**
     * The registrant\'s address.
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'address'?: string;
    /**
     * The registrant\'s city.
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'city'?: string;
    /**
     * The registrant\'s questions and comments.
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'comments'?: string;
    /**
     * The registrant\'s two-letter [country code](https://developers.zoom.us/docs/api/rest/other-references/abbreviation-lists/#countries).
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'country'?: string;
    /**
     * Information about custom questions.
     * @type {Array<MeetingsListRegistrantsResponseRegistrantsInnerCustomQuestionsInner>}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'custom_questions'?: Array<MeetingsListRegistrantsResponseRegistrantsInnerCustomQuestionsInner>;
    /**
     * The registrant\'s email address. See [Email address display rules](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#email-address-display-rules) for return value details.
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'email': string;
    /**
     * The registrant\'s first name.
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'first_name': string;
    /**
     * The registrant\'s industry.
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'industry'?: string;
    /**
     * The registrant\'s job title.
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'job_title'?: string;
    /**
     * The registrant\'s last name.
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'last_name'?: string;
    /**
     * The registrant\'s number of employees.  * `1-20`  * `21-50`  * `51-100`  * `101-250`  * `251-500`  * `501-1,000`  * `1,001-5,000`  * `5,001-10,000`  * `More than 10,000`
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'no_of_employees'?: MeetingsListRegistrantsResponseRegistrantsInnerNoOfEmployeesEnum;
    /**
     * The registrant\'s organization.
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'org'?: string;
    /**
     * The registrant\'s phone number.
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'phone'?: string;
    /**
     * The registrant\'s purchasing time frame.  * `Within a month`  * `1-3 months`  * `4-6 months`  * `More than 6 months`  * `No timeframe`
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'purchasing_time_frame'?: MeetingsListRegistrantsResponseRegistrantsInnerPurchasingTimeFrameEnum;
    /**
     * The registrant\'s role in the purchase process.  * `Decision Maker`  * `Evaluator/Recommender`  * `Influencer`  * `Not involved`
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'role_in_purchase_process'?: MeetingsListRegistrantsResponseRegistrantsInnerRoleInPurchaseProcessEnum;
    /**
     * The registrant\'s state or province.
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'state'?: string;
    /**
     * The status of the registrant\'s registration.      `approved`: User has been successfully approved for the webinar.     `pending`:  The registration is still pending.     `denied`: User has been denied from joining the webinar.
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'status'?: MeetingsListRegistrantsResponseRegistrantsInnerStatusEnum;
    /**
     * The registrant\'s ZIP or postal code.
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'zip'?: string;
    /**
     * The time at which the registrant registered.
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'create_time'?: string;
    /**
     * The URL using which an approved registrant can join the meeting or webinar.
     * @type {string}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'join_url'?: string;
    /**
     * The participant PIN code is used to authenticate audio participants before they join the meeting.
     * @type {number}
     * @memberof MeetingsListRegistrantsResponseRegistrantsInner
     */
    'participant_pin_code'?: number;
}

type MeetingsListRegistrantsResponseRegistrantsInnerNoOfEmployeesEnum = '' | '1-20' | '21-50' | '51-100' | '101-250' | '251-500' | '501-1,000' | '1,001-5,000' | '5,001-10,000' | 'More than 10,000'
type MeetingsListRegistrantsResponseRegistrantsInnerPurchasingTimeFrameEnum = '' | 'Within a month' | '1-3 months' | '4-6 months' | 'More than 6 months' | 'No timeframe'
type MeetingsListRegistrantsResponseRegistrantsInnerRoleInPurchaseProcessEnum = '' | 'Decision Maker' | 'Evaluator/Recommender' | 'Influencer' | 'Not involved'
type MeetingsListRegistrantsResponseRegistrantsInnerStatusEnum = 'approved' | 'denied' | 'pending'


