/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MeetingsListPastMeetingPollsResponseQuestionsInnerQuestionDetailsInner
 */
export interface MeetingsListPastMeetingPollsResponseQuestionsInnerQuestionDetailsInner {
    /**
     * Answer submitted by the user.
     * @type {string}
     * @memberof MeetingsListPastMeetingPollsResponseQuestionsInnerQuestionDetailsInner
     */
    'answer'?: string;
    /**
     * Date and time at which the answer to the poll was submitted.
     * @type {string}
     * @memberof MeetingsListPastMeetingPollsResponseQuestionsInnerQuestionDetailsInner
     */
    'date_time'?: string;
    /**
     * Unique identifier of the poll.
     * @type {string}
     * @memberof MeetingsListPastMeetingPollsResponseQuestionsInnerQuestionDetailsInner
     */
    'polling_id'?: string;
    /**
     * Question asked during the poll.
     * @type {string}
     * @memberof MeetingsListPastMeetingPollsResponseQuestionsInnerQuestionDetailsInner
     */
    'question'?: string;
}

