/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsLivestreamStatusUpdateRequestSettings } from './meetings-livestream-status-update-request-settings';

/**
 * Meeting live stream status.
 * @export
 * @interface MeetingsLivestreamStatusUpdateRequest
 */
export interface MeetingsLivestreamStatusUpdateRequest {
    /**
     * Update the status of a live stream.  The value can be one of the following:     `start`: Start a live stream.      `stop`: Stop an ongoing live stream.
     * @type {string}
     * @memberof MeetingsLivestreamStatusUpdateRequest
     */
    'action'?: MeetingsLivestreamStatusUpdateRequestActionEnum;
    /**
     * 
     * @type {MeetingsLivestreamStatusUpdateRequestSettings}
     * @memberof MeetingsLivestreamStatusUpdateRequest
     */
    'settings'?: MeetingsLivestreamStatusUpdateRequestSettings;
}

type MeetingsLivestreamStatusUpdateRequestActionEnum = 'start' | 'stop'


