/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsGetPollResponseQuestionsInner } from './meetings-get-poll-response-questions-inner';

/**
 * Information about meeting and webinar polling.
 * @export
 * @interface MeetingsGetPollResponse
 */
export interface MeetingsGetPollResponse {
    /**
     * The poll\'s title, up to 64 characters.
     * @type {string}
     * @memberof MeetingsGetPollResponse
     */
    'title'?: string;
    /**
     * Meeting Poll ID
     * @type {string}
     * @memberof MeetingsGetPollResponse
     */
    'id'?: string;
    /**
     * Status of the Meeting Poll:    `notstart` - Poll not started    `started` - Poll started    `ended` - Poll ended    `sharing` - Sharing poll results
     * @type {string}
     * @memberof MeetingsGetPollResponse
     */
    'status'?: MeetingsGetPollResponseStatusEnum;
    /**
     * Allow meeting participants to answer poll questions anonymously.   This value defaults to `false`.
     * @type {boolean}
     * @memberof MeetingsGetPollResponse
     */
    'anonymous'?: boolean;
    /**
     * The type of poll:  * `1` &mdash; Poll.  * `2` &mdash; Advanced Poll. This feature must be enabled in your Zoom account.  * `3` &mdash; Quiz. This feature must be enabled in your Zoom account.    This value defaults to `1`.
     * @type {number}
     * @memberof MeetingsGetPollResponse
     */
    'poll_type'?: MeetingsGetPollResponsePollTypeEnum;
    /**
     * Information about the poll\'s questions.
     * @type {Array<MeetingsGetPollResponseQuestionsInner>}
     * @memberof MeetingsGetPollResponse
     */
    'questions'?: Array<MeetingsGetPollResponseQuestionsInner>;
}

type MeetingsGetPollResponseStatusEnum = 'notstart' | 'started' | 'ended' | 'sharing'
type MeetingsGetPollResponsePollTypeEnum = 1 | 2 | 3


