/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The summary detail object.
 * @export
 * @interface MeetingsGetMeetingSummaryResponseSummaryDetailsInner
 */
export interface MeetingsGetMeetingSummaryResponseSummaryDetailsInner {
    /**
     * The summary content.
     * @type {string}
     * @memberof MeetingsGetMeetingSummaryResponseSummaryDetailsInner
     */
    'summary'?: string;
    /**
     * The summary label.
     * @type {string}
     * @memberof MeetingsGetMeetingSummaryResponseSummaryDetailsInner
     */
    'label'?: string;
}

