/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about the meeting\'s encoded SIP URI.
 * @export
 * @interface MeetingsGetSipUriWithPasscodeResponse
 */
export interface MeetingsGetSipUriWithPasscodeResponse {
    /**
     * The meeting\'s encoded SIP URI.
     * @type {string}
     * @memberof MeetingsGetSipUriWithPasscodeResponse
     */
    'sip_dialing'?: string;
    /**
     * Whether the API caller has a CRC (Conference Room Connector) plan.
     * @type {boolean}
     * @memberof MeetingsGetSipUriWithPasscodeResponse
     */
    'paid_crc_plan_participant'?: boolean;
    /**
     * This value identifies the meeting participant. It is automatically embedded in the SIP URI if the API caller has a CRC (Conference Room Connector) plan.
     * @type {string}
     * @memberof MeetingsGetSipUriWithPasscodeResponse
     */
    'participant_identifier_code'?: string;
    /**
     * The number of seconds the encoded SIP URI is valid before it expires.
     * @type {number}
     * @memberof MeetingsGetSipUriWithPasscodeResponse
     */
    'expire_in'?: number;
}

