/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MeetingsUpdateRegistrationQuestionsRequestCustomQuestionsInner
 */
export interface MeetingsUpdateRegistrationQuestionsRequestCustomQuestionsInner {
    /**
     * Title of the custom question.
     * @type {string}
     * @memberof MeetingsUpdateRegistrationQuestionsRequestCustomQuestionsInner
     */
    'title'?: string;
    /**
     * Answer choices for the question. Can not be used for `short` question type as this type of question requires registrants to type out the answer.
     * @type {Array<string>}
     * @memberof MeetingsUpdateRegistrationQuestionsRequestCustomQuestionsInner
     */
    'answers'?: Array<string>;
    /**
     * Indicates whether or not the custom question is required to be answered by participants or not.
     * @type {boolean}
     * @memberof MeetingsUpdateRegistrationQuestionsRequestCustomQuestionsInner
     */
    'required'?: boolean;
    /**
     * Type of the question being asked.
     * @type {string}
     * @memberof MeetingsUpdateRegistrationQuestionsRequestCustomQuestionsInner
     */
    'type'?: MeetingsUpdateRegistrationQuestionsRequestCustomQuestionsInnerTypeEnum;
}

type MeetingsUpdateRegistrationQuestionsRequestCustomQuestionsInnerTypeEnum = 'short' | 'single'


