/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MeetingsGetDetails200Response
 */
export interface MeetingsGetDetails200Response {
    /**
     * The [meeting ID](https://support.zoom.us/hc/en-us/articles/201362373-What-is-a-Meeting-ID).
     * @type {number}
     * @memberof MeetingsGetDetails200Response
     */
    'id'?: number;
    /**
     * The meeting\'s UUID. You **must** [double encode](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis/#meeting-id-and-uuid) this value if the meeting UUID begins with a `/` character or contains the `//` character.
     * @type {string}
     * @memberof MeetingsGetDetails200Response
     */
    'uuid'?: string;
    /**
     * The meeting\'s duration, in minutes.
     * @type {number}
     * @memberof MeetingsGetDetails200Response
     */
    'duration'?: number;
    /**
     * The meeting\'s start date and time.
     * @type {string}
     * @memberof MeetingsGetDetails200Response
     */
    'start_time'?: string;
    /**
     * The meeting\'s end date and time.
     * @type {string}
     * @memberof MeetingsGetDetails200Response
     */
    'end_time'?: string;
    /**
     * The host\'s ID.
     * @type {string}
     * @memberof MeetingsGetDetails200Response
     */
    'host_id'?: string;
    /**
     * The meeting host\'s department.
     * @type {string}
     * @memberof MeetingsGetDetails200Response
     */
    'dept'?: string;
    /**
     * The number of meeting participants.
     * @type {number}
     * @memberof MeetingsGetDetails200Response
     */
    'participants_count'?: number;
    /**
     * Whether the meeting was created directly through Zoom or via an API request:  * If the meeting was created via an OAuth app, this field returns the OAuth app\'s name.  * If the meeting was created via JWT or the Zoom Web Portal, this returns the `Zoom` value.
     * @type {string}
     * @memberof MeetingsGetDetails200Response
     */
    'source'?: string;
    /**
     * The meeting\'s topic.
     * @type {string}
     * @memberof MeetingsGetDetails200Response
     */
    'topic'?: string;
    /**
     * The total number of minutes attended by the meeting\'s host and participants.
     * @type {number}
     * @memberof MeetingsGetDetails200Response
     */
    'total_minutes'?: number;
    /**
     * The meeting type:  * `0` &mdash; A prescheduled meeting.  * `1` &mdash; An instant meeting.  * `2` &mdash; A scheduled meeting.  * `3` &mdash; A recurring meeting with no fixed time.  * `4` &mdash; A [personal meeting room](https://support.zoom.us/hc/en-us/articles/201362843).  * `7` &mdash; A [PAC (Personal Audio Conference)](https://support.zoom.us/hc/en-us/articles/205172455-Hosting-a-Personal-Audio-Conference-PAC-meeting) meeting.  * `8` &mdash; A recurring meeting with a fixed time.
     * @type {number}
     * @memberof MeetingsGetDetails200Response
     */
    'type'?: MeetingsGetDetails200ResponseTypeEnum;
    /**
     * The user\'s email address.
     * @type {string}
     * @memberof MeetingsGetDetails200Response
     */
    'user_email'?: string;
    /**
     * The user\'s display name.
     * @type {string}
     * @memberof MeetingsGetDetails200Response
     */
    'user_name'?: string;
}

type MeetingsGetDetails200ResponseTypeEnum = 0 | 1 | 2 | 3 | 4 | 7 | 8


