/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Occurrence object. This object is only returned for recurring meetings.
 * @export
 * @interface MeetingsGetDetailsResponseOccurrencesInner
 */
export interface MeetingsGetDetailsResponseOccurrencesInner {
    /**
     * Duration.
     * @type {number}
     * @memberof MeetingsGetDetailsResponseOccurrencesInner
     */
    'duration'?: number;
    /**
     * Occurrence ID: Unique Identifier that identifies an occurrence of a recurring meeting. [Recurring meetings](https://support.zoom.us/hc/en-us/articles/214973206-Scheduling-Recurring-Meetings) can have a maximum of 50 occurrences.
     * @type {string}
     * @memberof MeetingsGetDetailsResponseOccurrencesInner
     */
    'occurrence_id'?: string;
    /**
     * Start time.
     * @type {string}
     * @memberof MeetingsGetDetailsResponseOccurrencesInner
     */
    'start_time'?: string;
    /**
     * Occurrence status:   `available` - Available occurrence.    `deleted` -  Deleted occurrence.
     * @type {string}
     * @memberof MeetingsGetDetailsResponseOccurrencesInner
     */
    'status'?: MeetingsGetDetailsResponseOccurrencesInnerStatusEnum;
}

type MeetingsGetDetailsResponseOccurrencesInnerStatusEnum = 'available' | 'deleted'


