/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsControlInMeetingFeaturesRequestParamsSipHeadersAdditionalHeadersInner } from './meetings-control-in-meeting-features-request-params-sip-headers-additional-headers-inner';

/**
 * Enable customers to leverage services that require customization of the FROM header to identify the caller. Use this field if you pass the `participant.invite.room_system_callout` value for the `method` field and the `sip` value for the `call_type` field.
 * @export
 * @interface MeetingsControlInMeetingFeaturesRequestParamsSipHeaders
 */
export interface MeetingsControlInMeetingFeaturesRequestParamsSipHeaders {
    /**
     * Custom name that will be used within the SIP Header.
     * @type {string}
     * @memberof MeetingsControlInMeetingFeaturesRequestParamsSipHeaders
     */
    'from_display_name'?: string;
    /**
     * Custom remote name that will be used within the meeting.
     * @type {string}
     * @memberof MeetingsControlInMeetingFeaturesRequestParamsSipHeaders
     */
    'to_display_name'?: string;
    /**
     * Custom URI that will be used within the SIP Header. The URI must start with \'sip:\' or \'sips:\' as a valid URI based on parameters defined by the platform.
     * @type {string}
     * @memberof MeetingsControlInMeetingFeaturesRequestParamsSipHeaders
     */
    'from_uri'?: string;
    /**
     * Ability to add 1 to 10 custom headers, each of which has a maximum length of 256 bytes to comply with SIP standards.  Custom headers would leverage header names starting with \'X-\' per SIP guidelines.
     * @type {Array<MeetingsControlInMeetingFeaturesRequestParamsSipHeadersAdditionalHeadersInner>}
     * @memberof MeetingsControlInMeetingFeaturesRequestParamsSipHeaders
     */
    'additional_headers'?: Array<MeetingsControlInMeetingFeaturesRequestParamsSipHeadersAdditionalHeadersInner>;
}

