/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MeetingsCreateTemplateFromMeetingResponse
 */
export interface MeetingsCreateTemplateFromMeetingResponse {
    /**
     * The template ID.
     * @type {string}
     * @memberof MeetingsCreateTemplateFromMeetingResponse
     */
    'id'?: string;
    /**
     * The template name.
     * @type {string}
     * @memberof MeetingsCreateTemplateFromMeetingResponse
     */
    'name'?: string;
}

