/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The list of approved or blocked users from specific countries or regions who can join the meeting.
 * @export
 * @interface MeetingsCreateMeetingRequestSettingsApprovedOrDeniedCountriesOrRegions
 */
export interface MeetingsCreateMeetingRequestSettingsApprovedOrDeniedCountriesOrRegions {
    /**
     * The list of approved countries or regions.
     * @type {Array<string>}
     * @memberof MeetingsCreateMeetingRequestSettingsApprovedOrDeniedCountriesOrRegions
     */
    'approved_list'?: Array<string>;
    /**
     * The list of blocked countries or regions.
     * @type {Array<string>}
     * @memberof MeetingsCreateMeetingRequestSettingsApprovedOrDeniedCountriesOrRegions
     */
    'denied_list'?: Array<string>;
    /**
     * Whether to enable the [**Approve or block entry for users from specific countries/regions**](https://support.zoom.us/hc/en-us/articles/360060086231-Approve-or-block-entry-for-users-from-specific-countries-regions) setting.
     * @type {boolean}
     * @memberof MeetingsCreateMeetingRequestSettingsApprovedOrDeniedCountriesOrRegions
     */
    'enable'?: boolean;
    /**
     * Whether to allow or block users from specific countries or regions. * `approve` - Allow users from specific countries or regions to join the meeting. If you select this setting, include the approved countries or regions in the `approved_list` field.  * `deny` - Block users from specific countries or regions from joining the meeting. If you select this setting, include the blocked countries or regions in the `denied_list` field.
     * @type {string}
     * @memberof MeetingsCreateMeetingRequestSettingsApprovedOrDeniedCountriesOrRegions
     */
    'method'?: MeetingsCreateMeetingRequestSettingsApprovedOrDeniedCountriesOrRegionsMethodEnum;
}

type MeetingsCreateMeetingRequestSettingsApprovedOrDeniedCountriesOrRegionsMethodEnum = 'approve' | 'deny'


