/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsGetPollResponseQuestionsInnerPromptsInner } from './meetings-get-poll-response-questions-inner-prompts-inner';

/**
 * 
 * @export
 * @interface MeetingsGetPollResponseQuestionsInner
 */
export interface MeetingsGetPollResponseQuestionsInner {
    /**
     * The allowed maximum number of characters. This field only applies to `short_answer` and `long_answer` polls:  * For `short_answer` polls, a maximum of 500 characters.  * For `long_answer` polls, a maximum of 2,000 characters.
     * @type {number}
     * @memberof MeetingsGetPollResponseQuestionsInner
     */
    'answer_max_character'?: number;
    /**
     * The allowed minimum number of characters. This field only applies to `short_answer` and `long_answer` polls. You must provide at least a **one** character minimum value.
     * @type {number}
     * @memberof MeetingsGetPollResponseQuestionsInner
     */
    'answer_min_character'?: number;
    /**
     * Whether participants must answer the question:  * `true` &mdash; The participant must answer the question.  * `false` &mdash; The participant does not need to answer the question.   **Note:**  * When the poll\'s `type` value is `1` (Poll), this value defaults to `true`.  * When the poll\'s `type` value is the `2` (Advanced Poll) or `3` (Quiz) values, this value defaults to `false`.
     * @type {boolean}
     * @memberof MeetingsGetPollResponseQuestionsInner
     */
    'answer_required'?: boolean;
    /**
     * The poll question\'s available answers. This field requires a **minimum** of two answers.   * For `single` and `multiple` polls, you can only provide a maximum of 10 answers.  * For `matching` polls, you can only provide a maximum of 16 answers.  * For `rank_order` polls, you can only provide a maximum of seven answers.
     * @type {Array<string>}
     * @memberof MeetingsGetPollResponseQuestionsInner
     */
    'answers'?: Array<string>;
    /**
     * Whether the correct answer is case sensitive. This field only applies to `fill_in_the_blank` polls:  * `true` &mdash; The answer is case-sensitive.  * `false` &mdash; The answer is not case-sensitive.   This value defaults to `false`.
     * @type {boolean}
     * @memberof MeetingsGetPollResponseQuestionsInner
     */
    'case_sensitive'?: boolean;
    /**
     * The poll question, up to 255 characters.   For `fill_in_the_blank` polls, this field is the poll\'s question. For each value that the user must fill in, ensure that there are the same number of `right_answers` values.
     * @type {string}
     * @memberof MeetingsGetPollResponseQuestionsInner
     */
    'name'?: string;
    /**
     * Information about the prompt questions. This field only applies to `matching` and `rank_order` polls. You **must** provide a minimum of two prompts, up to a maximum of 10 prompts.
     * @type {Array<MeetingsGetPollResponseQuestionsInnerPromptsInner>}
     * @memberof MeetingsGetPollResponseQuestionsInner
     */
    'prompts'?: Array<MeetingsGetPollResponseQuestionsInnerPromptsInner>;
    /**
     * The high score label used for the `rating_max_value` field.   This field only applies to the `rating_scale` poll.
     * @type {string}
     * @memberof MeetingsGetPollResponseQuestionsInner
     */
    'rating_max_label'?: string;
    /**
     * The rating scale\'s maximum value, up to a maximum value of 10.   This field only applies to the `rating_scale` poll.
     * @type {number}
     * @memberof MeetingsGetPollResponseQuestionsInner
     */
    'rating_max_value'?: number;
    /**
     * The low score label used for the `rating_min_value` field.   This field only applies to the `rating_scale` poll.
     * @type {string}
     * @memberof MeetingsGetPollResponseQuestionsInner
     */
    'rating_min_label'?: string;
    /**
     * The rating scale\'s minimum value. This value cannot be less than zero.   This field only applies to the `rating_scale` poll.
     * @type {number}
     * @memberof MeetingsGetPollResponseQuestionsInner
     */
    'rating_min_value'?: number;
    /**
     * The poll question\'s correct answer(s). This field is **required** if the poll\'s `type` value is `3` (Quiz).    For `single` and `matching` polls, this field only accepts one answer.
     * @type {Array<string>}
     * @memberof MeetingsGetPollResponseQuestionsInner
     */
    'right_answers'?: Array<string>;
    /**
     * Whether to display the radio selection as a drop-down box:  * `true` &mdash; Show as a drop-down box.  * `false` &mdash; Do not show as a drop-down box.   This value defaults to `false`.
     * @type {boolean}
     * @memberof MeetingsGetPollResponseQuestionsInner
     */
    'show_as_dropdown'?: boolean;
    /**
     * The poll\'s question and answer type:  * `single` &mdash; Single choice.  * `multiple` &mdash; Multiple choice.  * `matching` &mdash; Matching.  * `rank_order` &mdash; Rank order.  * `short_answer` &mdash; Short answer.  * `long_answer` &mdash; Long answer.  * `fill_in_the_blank` &mdash; Fill in the blank.  * `rating_scale` &mdash; Rating scale.
     * @type {string}
     * @memberof MeetingsGetPollResponseQuestionsInner
     */
    'type'?: MeetingsGetPollResponseQuestionsInnerTypeEnum;
}

type MeetingsGetPollResponseQuestionsInnerTypeEnum = 'single' | 'multiple' | 'matching' | 'rank_order' | 'short_answer' | 'long_answer' | 'fill_in_the_blank' | 'rating_scale'


