/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MeetingsListUpcomingMeetingsResponseMeetingsInner } from './meetings-list-upcoming-meetings-response-meetings-inner';

/**
 * 
 * @export
 * @interface MeetingsListUpcomingMeetingsResponse
 */
export interface MeetingsListUpcomingMeetingsResponse {
    /**
     * The total number of all records available across all pages.
     * @type {number}
     * @memberof MeetingsListUpcomingMeetingsResponse
     */
    'total_records'?: number;
    /**
     * List of upcoming meeting objects.
     * @type {Array<MeetingsListUpcomingMeetingsResponseMeetingsInner>}
     * @memberof MeetingsListUpcomingMeetingsResponse
     */
    'meetings'?: Array<MeetingsListUpcomingMeetingsResponseMeetingsInner>;
}

