/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PacListAccountsResponsePacAccountsInner } from './pac-list-accounts-response-pac-accounts-inner';

/**
 * 
 * @export
 * @interface PacListAccountsResponse
 */
export interface PacListAccountsResponse {
    /**
     * Information about the PAC accounts.
     * @type {Array<PacListAccountsResponsePacAccountsInner>}
     * @memberof PacListAccountsResponse
     */
    'pac_accounts'?: Array<PacListAccountsResponsePacAccountsInner>;
}

