/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PacListAccountsResponsePacAccountsInnerDedicatedDialInNumberInner } from './pac-list-accounts-response-pac-accounts-inner-dedicated-dial-in-number-inner';
import { PacListAccountsResponsePacAccountsInnerGlobalDialInNumbersInner } from './pac-list-accounts-response-pac-accounts-inner-global-dial-in-numbers-inner';

/**
 * 
 * @export
 * @interface PacListAccountsResponsePacAccountsInner
 */
export interface PacListAccountsResponsePacAccountsInner {
    /**
     * The conference ID.
     * @type {number}
     * @memberof PacListAccountsResponsePacAccountsInner
     */
    'conference_id'?: number;
    /**
     * Information about the account\'s dedicated dial-in numbers.
     * @type {Array<PacListAccountsResponsePacAccountsInnerDedicatedDialInNumberInner>}
     * @memberof PacListAccountsResponsePacAccountsInner
     */
    'dedicated_dial_in_number'?: Array<PacListAccountsResponsePacAccountsInnerDedicatedDialInNumberInner>;
    /**
     * Information about the account\'s global dial-in numbers.
     * @type {Array<PacListAccountsResponsePacAccountsInnerGlobalDialInNumbersInner>}
     * @memberof PacListAccountsResponsePacAccountsInner
     */
    'global_dial_in_numbers'?: Array<PacListAccountsResponsePacAccountsInnerGlobalDialInNumbersInner>;
    /**
     * The listen-only password, up to six characters in length.
     * @type {string}
     * @memberof PacListAccountsResponsePacAccountsInner
     */
    'listen_only_password'?: string;
    /**
     * The participant password, up to six characters in length.
     * @type {string}
     * @memberof PacListAccountsResponsePacAccountsInner
     */
    'participant_password'?: string;
}

