/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReportsGetWebinarPollReportsResponseQuestionsInnerQuestionDetailsInner
 */
export interface ReportsGetWebinarPollReportsResponseQuestionsInnerQuestionDetailsInner {
    /**
     * The user\'s given answer.
     * @type {string}
     * @memberof ReportsGetWebinarPollReportsResponseQuestionsInnerQuestionDetailsInner
     */
    'answer'?: string;
    /**
     * The date and time at which the user answered the poll question.
     * @type {string}
     * @memberof ReportsGetWebinarPollReportsResponseQuestionsInnerQuestionDetailsInner
     */
    'date_time'?: string;
    /**
     * The poll\'s ID.
     * @type {string}
     * @memberof ReportsGetWebinarPollReportsResponseQuestionsInnerQuestionDetailsInner
     */
    'polling_id'?: string;
    /**
     * The poll question.
     * @type {string}
     * @memberof ReportsGetWebinarPollReportsResponseQuestionsInnerQuestionDetailsInner
     */
    'question'?: string;
}

