/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReportsGetCloudRecordingUsageReportResponseCloudRecordingStorageInner } from './reports-get-cloud-recording-usage-report-response-cloud-recording-storage-inner';

/**
 * 
 * @export
 * @interface ReportsGetCloudRecordingUsageReportResponse
 */
export interface ReportsGetCloudRecordingUsageReportResponse {
    /**
     * Start date for this report
     * @type {string}
     * @memberof ReportsGetCloudRecordingUsageReportResponse
     */
    'from'?: string;
    /**
     * End date for this report
     * @type {string}
     * @memberof ReportsGetCloudRecordingUsageReportResponse
     */
    'to'?: string;
    /**
     * Array of cloud usage objects
     * @type {Array<ReportsGetCloudRecordingUsageReportResponseCloudRecordingStorageInner>}
     * @memberof ReportsGetCloudRecordingUsageReportResponse
     */
    'cloud_recording_storage'?: Array<ReportsGetCloudRecordingUsageReportResponseCloudRecordingStorageInner>;
}

