/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReportsGetBillingInvoicesResponseInvoicesInner
 */
export interface ReportsGetBillingInvoicesResponseInvoicesInner {
    /**
     * End date of the invoice period.
     * @type {string}
     * @memberof ReportsGetBillingInvoicesResponseInvoicesInner
     */
    'end_date'?: string;
    /**
     * Name of the invoice.
     * @type {string}
     * @memberof ReportsGetBillingInvoicesResponseInvoicesInner
     */
    'invoice_charge_name'?: string;
    /**
     * Invoice number 
     * @type {string}
     * @memberof ReportsGetBillingInvoicesResponseInvoicesInner
     */
    'invoice_number'?: string;
    /**
     * Number of licenses bought.
     * @type {number}
     * @memberof ReportsGetBillingInvoicesResponseInvoicesInner
     */
    'quantity'?: number;
    /**
     * Start date of the invoice period.
     * @type {string}
     * @memberof ReportsGetBillingInvoicesResponseInvoicesInner
     */
    'start_date'?: string;
    /**
     * Tax amount in the invoice.
     * @type {string}
     * @memberof ReportsGetBillingInvoicesResponseInvoicesInner
     */
    'tax_amount'?: string;
    /**
     * Total billed amount in the invoice.
     * @type {string}
     * @memberof ReportsGetBillingInvoicesResponseInvoicesInner
     */
    'total_amount'?: string;
}

