/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReportsGetWebinarSurveyReportResponseSurveyAnswersInnerAnswerDetailsInner
 */
export interface ReportsGetWebinarSurveyReportResponseSurveyAnswersInnerAnswerDetailsInner {
    /**
     * The survey question.
     * @type {string}
     * @memberof ReportsGetWebinarSurveyReportResponseSurveyAnswersInnerAnswerDetailsInner
     */
    'question'?: string;
    /**
     * The question\'s ID
     * @type {string}
     * @memberof ReportsGetWebinarSurveyReportResponseSurveyAnswersInnerAnswerDetailsInner
     */
    'question_id'?: string;
    /**
     * The user\'s given answer.
     * @type {string}
     * @memberof ReportsGetWebinarSurveyReportResponseSurveyAnswersInnerAnswerDetailsInner
     */
    'answer'?: string;
    /**
     * The date and time at which the user answered the survey question.
     * @type {string}
     * @memberof ReportsGetWebinarSurveyReportResponseSurveyAnswersInnerAnswerDetailsInner
     */
    'date_time'?: string;
}

