/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReportsGetMeetingQaReportResponseQuestionsInnerQuestionDetailsInnerAnswerDetailsInner } from './reports-get-meeting-qa-report-response-questions-inner-question-details-inner-answer-details-inner';

/**
 * 
 * @export
 * @interface ReportsGetMeetingQaReportResponseQuestionsInnerQuestionDetailsInner
 */
export interface ReportsGetMeetingQaReportResponseQuestionsInnerQuestionDetailsInner {
    /**
     * The given answer. If this is a live answer, the value is \'live answered\'. **Note:** All answers will be returned together and separated by semicolons. For more detailed answer information, please see the \"answer_details\" field.
     * @type {string}
     * @memberof ReportsGetMeetingQaReportResponseQuestionsInnerQuestionDetailsInner
     * @deprecated
     */
    'answer'?: string;
    /**
     * Asked question.
     * @type {string}
     * @memberof ReportsGetMeetingQaReportResponseQuestionsInnerQuestionDetailsInner
     */
    'question'?: string;
    /**
     * Question UUID.
     * @type {string}
     * @memberof ReportsGetMeetingQaReportResponseQuestionsInnerQuestionDetailsInner
     */
    'question_id'?: string;
    /**
     * Question create time.
     * @type {string}
     * @memberof ReportsGetMeetingQaReportResponseQuestionsInnerQuestionDetailsInner
     */
    'create_time'?: string;
    /**
     * Array of answers from the user.
     * @type {Array<ReportsGetMeetingQaReportResponseQuestionsInnerQuestionDetailsInnerAnswerDetailsInner>}
     * @memberof ReportsGetMeetingQaReportResponseQuestionsInnerQuestionDetailsInner
     */
    'answer_details'?: Array<ReportsGetMeetingQaReportResponseQuestionsInnerQuestionDetailsInnerAnswerDetailsInner>;
}

