/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReportsGetWebinarSurveyReportResponseSurveyAnswersInnerAnswerDetailsInner } from './reports-get-webinar-survey-report-response-survey-answers-inner-answer-details-inner';

/**
 * 
 * @export
 * @interface ReportsGetWebinarSurveyReportResponseSurveyAnswersInner
 */
export interface ReportsGetWebinarSurveyReportResponseSurveyAnswersInner {
    /**
     * The participant\'s email address.
     * @type {string}
     * @memberof ReportsGetWebinarSurveyReportResponseSurveyAnswersInner
     */
    'email'?: string;
    /**
     * The participant\'s display name. **Allow participants to answer questions anonymously** setting is enabled for a [survey](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0057559), the participant\'s survey information is kept anonymous and the `name` field will return the &quot;Anonymous Attendee&quot; value.
     * @type {string}
     * @memberof ReportsGetWebinarSurveyReportResponseSurveyAnswersInner
     */
    'name'?: string;
    /**
     * The participant\'s first name. If the **Allow participants to answer questions anonymously** setting is enabled for a [survey](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0057559), the participant\'s survey information is kept anonymous and the `first_name` field will return the &quot;Anonymous Attendee&quot; value.
     * @type {string}
     * @memberof ReportsGetWebinarSurveyReportResponseSurveyAnswersInner
     */
    'first_name'?: string;
    /**
     * The participant\'s last name. If the **Allow participants to answer questions anonymously** setting is enabled for a [survey](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0057559), the participant\'s survey information is kept anonymous and the `last_name` field will return the &quot;Anonymous Attendee&quot; value.
     * @type {string}
     * @memberof ReportsGetWebinarSurveyReportResponseSurveyAnswersInner
     */
    'last_name'?: string;
    /**
     * Information about the user\'s questions and answers.
     * @type {Array<ReportsGetWebinarSurveyReportResponseSurveyAnswersInnerAnswerDetailsInner>}
     * @memberof ReportsGetWebinarSurveyReportResponseSurveyAnswersInner
     */
    'answer_details'?: Array<ReportsGetWebinarSurveyReportResponseSurveyAnswersInnerAnswerDetailsInner>;
}

