/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReportsGetMeetingDetailReportsResponseCustomKeysInner
 */
export interface ReportsGetMeetingDetailReportsResponseCustomKeysInner {
    /**
     * Custom key associated with the user.
     * @type {string}
     * @memberof ReportsGetMeetingDetailReportsResponseCustomKeysInner
     */
    'key'?: string;
    /**
     * Value of the custom key associated with the user.
     * @type {string}
     * @memberof ReportsGetMeetingDetailReportsResponseCustomKeysInner
     */
    'value'?: string;
}

