/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReportsListUpcomingEventsReportResponseUpcomingEventsInner } from './reports-list-upcoming-events-report-response-upcoming-events-inner';

/**
 * 
 * @export
 * @interface ReportsListUpcomingEventsReportResponse
 */
export interface ReportsListUpcomingEventsReportResponse {
    /**
     * The report\'s start date. This value must be within the past six months.
     * @type {string}
     * @memberof ReportsListUpcomingEventsReportResponse
     */
    'from'?: string;
    /**
     * The next page token is used to paginate through large result sets. A next page token returns when the set of available results exceeds the current page size. The expiration period for this token is 15 minutes.
     * @type {string}
     * @memberof ReportsListUpcomingEventsReportResponse
     */
    'next_page_token'?: string;
    /**
     * The number of records returned in a single API call.
     * @type {number}
     * @memberof ReportsListUpcomingEventsReportResponse
     */
    'page_size'?: number;
    /**
     * The report\'s end date. This value must be within the past six months and cannot exceed a month from the `from` value.
     * @type {string}
     * @memberof ReportsListUpcomingEventsReportResponse
     */
    'to'?: string;
    /**
     * Information about the upcoming event.
     * @type {Array<ReportsListUpcomingEventsReportResponseUpcomingEventsInner>}
     * @memberof ReportsListUpcomingEventsReportResponse
     */
    'upcoming_events'?: Array<ReportsListUpcomingEventsReportResponseUpcomingEventsInner>;
}

