/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReportsGetWebinarPollReportsResponseQuestionsInner } from './reports-get-webinar-poll-reports-response-questions-inner';

/**
 * 
 * @export
 * @interface ReportsGetWebinarPollReportsResponse
 */
export interface ReportsGetWebinarPollReportsResponse {
    /**
     * The webinar ID.
     * @type {number}
     * @memberof ReportsGetWebinarPollReportsResponse
     */
    'id'?: number;
    /**
     * Information about the webinar questions.
     * @type {Array<ReportsGetWebinarPollReportsResponseQuestionsInner>}
     * @memberof ReportsGetWebinarPollReportsResponse
     */
    'questions'?: Array<ReportsGetWebinarPollReportsResponseQuestionsInner>;
    /**
     * The webinar\'s start time.
     * @type {string}
     * @memberof ReportsGetWebinarPollReportsResponse
     */
    'start_time'?: string;
    /**
     * The webinar\'s universally unique identifier (UUID). Each webinar instance generates a webinar UUID.
     * @type {string}
     * @memberof ReportsGetWebinarPollReportsResponse
     */
    'uuid'?: string;
}

