/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReportsGetTelephoneReportsResponseTelephonyUsageInner
 */
export interface ReportsGetTelephoneReportsResponseTelephonyUsageInner {
    /**
     * Caller\'s call-in number.
     * @type {string}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'call_in_number'?: string;
    /**
     * Country name.
     * @type {string}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'country_name'?: string;
    /**
     * User department.
     * @type {string}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'dept'?: string;
    /**
     * Call leg duration
     * @type {number}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'duration'?: number;
    /**
     * Call leg end time
     * @type {string}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'end_time'?: string;
    /**
     * User email.
     * @type {string}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'host_email'?: string;
    /**
     * The user ID of the meeting host.
     * @type {string}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'host_id'?: string;
    /**
     * User display name.
     * @type {string}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'host_name'?: string;
    /**
     * [Meeting ID](https://support.zoom.us/hc/en-us/articles/201362373-What-is-a-Meeting-ID-): Unique identifier of the meeting in &quot;**long**&quot; format(represented as int64 data type in JSON), also known as the meeting number.
     * @type {number}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'meeting_id'?: number;
    /**
     * Meeting type.
     * @type {string}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'meeting_type'?: string;
    /**
     * Toll-free telephone number. 
     * @type {string}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'phone_number'?: string;
    /**
     * Calling rate for the telephone call.
     * @type {number}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'rate'?: number;
    /**
     * The number that is signaled to Zoom. 
     * @type {string}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'signaled_number'?: string;
    /**
     * Call leg start time
     * @type {string}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'start_time'?: string;
    /**
     * Total cost (USD) for Call Out. Calculated as plan rate by duration.
     * @type {number}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'total'?: number;
    /**
     * Call type.
     * @type {string}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'type'?: ReportsGetTelephoneReportsResponseTelephonyUsageInnerTypeEnum;
    /**
     * Meeting UUID.
     * @type {string}
     * @memberof ReportsGetTelephoneReportsResponseTelephonyUsageInner
     */
    'uuid'?: string;
}

type ReportsGetTelephoneReportsResponseTelephonyUsageInnerTypeEnum = 'toll-free' | 'call-out' | 'call-in' | 'US toll-number' | 'global toll-number' | 'premium' | 'premium call-in' | 'Toll'


