/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReportsGetBillingDepartmentReportsResponseBillingReportsInner
 */
export interface ReportsGetBillingDepartmentReportsResponseBillingReportsInner {
    /**
     * End date of the billing period.
     * @type {string}
     * @memberof ReportsGetBillingDepartmentReportsResponseBillingReportsInner
     */
    'end_date'?: string;
    /**
     * Unique Identifier of the report. Use this ID to retrieve billing invoice via the &quot;Get Billing Invoices API&quot;.   You can also use this ID to export a CSV file of the billing report from this URL: `https://zoom.us/account/report/billing/export?id={id}`.
     * @type {string}
     * @memberof ReportsGetBillingDepartmentReportsResponseBillingReportsInner
     */
    'id'?: string;
    /**
     * Start date of the billing period.
     * @type {string}
     * @memberof ReportsGetBillingDepartmentReportsResponseBillingReportsInner
     */
    'start_date'?: string;
    /**
     * Total tax amount for this billing period.
     * @type {string}
     * @memberof ReportsGetBillingDepartmentReportsResponseBillingReportsInner
     */
    'tax_amount'?: string;
    /**
     * Total billing amount for this billing period.
     * @type {string}
     * @memberof ReportsGetBillingDepartmentReportsResponseBillingReportsInner
     */
    'total_amount'?: string;
    /**
     * Type of the billing report. The value should be either of the following:     `0` - Detailed Billing Reports `1` - Custom Billing Reports
     * @type {number}
     * @memberof ReportsGetBillingDepartmentReportsResponseBillingReportsInner
     */
    'type'?: ReportsGetBillingDepartmentReportsResponseBillingReportsInnerTypeEnum;
}

type ReportsGetBillingDepartmentReportsResponseBillingReportsInnerTypeEnum = 0 | 1


