/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReportsGetDailyUsageReportResponseDatesInner } from './reports-get-daily-usage-report-response-dates-inner';

/**
 * 
 * @export
 * @interface ReportsGetDailyUsageReportResponse
 */
export interface ReportsGetDailyUsageReportResponse {
    /**
     * Array of date objects.
     * @type {Array<ReportsGetDailyUsageReportResponseDatesInner>}
     * @memberof ReportsGetDailyUsageReportResponse
     */
    'dates'?: Array<ReportsGetDailyUsageReportResponseDatesInner>;
    /**
     * Month for this report.
     * @type {number}
     * @memberof ReportsGetDailyUsageReportResponse
     */
    'month'?: number;
    /**
     * Year for this report.
     * @type {number}
     * @memberof ReportsGetDailyUsageReportResponse
     */
    'year'?: number;
}

