/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReportsGetActiveInactiveHostReportsResponse
 */
export interface ReportsGetActiveInactiveHostReportsResponse {
    /**
     * Start date for this report.
     * @type {string}
     * @memberof ReportsGetActiveInactiveHostReportsResponse
     */
    'from'?: string;
    /**
     * The next page token is used to paginate through large result sets. A next page token will be returned whenever the set of available results exceeds the current page size. The expiration period for this token is 15 minutes.
     * @type {string}
     * @memberof ReportsGetActiveInactiveHostReportsResponse
     */
    'next_page_token'?: string;
    /**
     * The number of pages returned for the request made.
     * @type {number}
     * @memberof ReportsGetActiveInactiveHostReportsResponse
     */
    'page_count'?: number;
    /**
     * The page number of the current results.
     * @type {number}
     * @memberof ReportsGetActiveInactiveHostReportsResponse
     */
    'page_number'?: number;
    /**
     * The number of records returned with a single API call.
     * @type {number}
     * @memberof ReportsGetActiveInactiveHostReportsResponse
     */
    'page_size'?: number;
    /**
     * End date for this report.
     * @type {string}
     * @memberof ReportsGetActiveInactiveHostReportsResponse
     */
    'to'?: string;
    /**
     * The total number of all the records available across pages.
     * @type {number}
     * @memberof ReportsGetActiveInactiveHostReportsResponse
     */
    'total_records'?: number;
    /**
     * Number of meeting minutes for this range.
     * @type {number}
     * @memberof ReportsGetActiveInactiveHostReportsResponse
     */
    'total_meeting_minutes'?: number;
    /**
     * Number of meetings for this range.
     * @type {number}
     * @memberof ReportsGetActiveInactiveHostReportsResponse
     */
    'total_meetings'?: number;
    /**
     * Number of participants for this range.
     * @type {number}
     * @memberof ReportsGetActiveInactiveHostReportsResponse
     */
    'total_participants'?: number;
    /**
     * Array of user objects.
     * @type {Array<object>}
     * @memberof ReportsGetActiveInactiveHostReportsResponse
     */
    'users'?: Array<object>;
}

