/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReportsGetCloudRecordingUsageReportResponseCloudRecordingStorageInner
 */
export interface ReportsGetCloudRecordingUsageReportResponseCloudRecordingStorageInner {
    /**
     * Date of the usage
     * @type {string}
     * @memberof ReportsGetCloudRecordingUsageReportResponseCloudRecordingStorageInner
     */
    'date'?: string;
    /**
     * Free storage
     * @type {string}
     * @memberof ReportsGetCloudRecordingUsageReportResponseCloudRecordingStorageInner
     */
    'free_usage'?: string;
    /**
     * Paid storage
     * @type {string}
     * @memberof ReportsGetCloudRecordingUsageReportResponseCloudRecordingStorageInner
     */
    'plan_usage'?: string;
    /**
     * Storage used on the date
     * @type {string}
     * @memberof ReportsGetCloudRecordingUsageReportResponseCloudRecordingStorageInner
     */
    'usage'?: string;
}

