/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SipPhoneEnableUserSipPhoneResponse
 */
export interface SipPhoneEnableUserSipPhoneResponse {
    /**
     * The SIP phone ID.
     * @type {string}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'id'?: string;
    /**
     * The authorization name of the user that is registered for SIP phone.
     * @type {string}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'authorization_name'?: string;
    /**
     * The name or IP address of your provider\'s SIP domain (example: CDC.WEB). 
     * @type {string}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'domain'?: string;
    /**
     * The password generated for the user in the SIP account.
     * @type {string}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'password'?: string;
    /**
     * The IP address of the proxy server for SIP requests. Note that if you are using the UDP transport protocol, the default port is 5060. If you are using UDP with a different port number, that port number must be included with the IP address. If you are not using a proxy server, this value can be the same as the Register Server.
     * @type {string}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'proxy_server'?: string;
    /**
     * The IP address of the proxy server for SIP requests. Note that if you are using the UDP transport protocol, the default port is 5060. If you are using UDP with a different port number, that port number must be included with the IP address. If you are not using a proxy server, this value can be the same as the Register Server, or empty.
     * @type {string}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'proxy_server2'?: string;
    /**
     * The IP address of the proxy server for SIP requests. Note that if you are using the UDP transport protocol, the default port is 5060. If you are using UDP with a different port number, that port number must be included with the IP address. If you are not using a proxy server, this value can be the same as the Register Server, or empty.
     * @type {string}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'proxy_server3'?: string;
    /**
     * The IP address of the server that accepts REGISTER requests. Note that if you are using the UDP transport protocol, the default port is 5060. If you are using UDP with a different port number, that port number must be included with the IP address.
     * @type {string}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'register_server'?: string;
    /**
     * The IP address of the server that accepts REGISTER requests. Note that if you are using the UDP transport protocol, the default port is 5060. If you are using UDP with a different port number, that port number must be included with the IP address.
     * @type {string}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'register_server2'?: string;
    /**
     * The IP address of the server that accepts REGISTER requests. Note that if you are using the UDP transport protocol, the default port is 5060. If you are using UDP with a different port number, that port number must be included with the IP address.
     * @type {string}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'register_server3'?: string;
    /**
     * The number of minutes after which the SIP registration of the Zoom client user will expire, and the client will auto register to the SIP server.
     * @type {number}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'registration_expire_time'?: number;
    /**
     * Protocols supported by the SIP provider.     The value must be either `UDP`, `TCP`, `TLS`, `AUTO`.
     * @type {string}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'transport_protocol'?: SipPhoneEnableUserSipPhoneResponseTransportProtocolEnum;
    /**
     * Protocols supported by the SIP provider.     The value must be either `UDP`, `TCP`, `TLS`, `AUTO`.
     * @type {string}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'transport_protocol2'?: SipPhoneEnableUserSipPhoneResponseTransportProtocol2Enum;
    /**
     * Protocols supported by the SIP provider.     The value must be either `UDP`, `TCP`, `TLS`, `AUTO`.
     * @type {string}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'transport_protocol3'?: SipPhoneEnableUserSipPhoneResponseTransportProtocol3Enum;
    /**
     * The email address of the user to associate with the SIP Phone. Can add `.win`, `.mac`, `.android`, `.ipad`, `.iphone`, `.linux`, `.pc`, `.mobile`, `.pad` at the end of the email (for example, `user@example.com.mac`) to add accounts for different platforms for the same user.
     * @type {string}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'user_email'?: string;
    /**
     * The phone number associated with the user in the SIP account.
     * @type {string}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'user_name'?: string;
    /**
     * The number to dial for checking voicemail.
     * @type {string}
     * @memberof SipPhoneEnableUserSipPhoneResponse
     */
    'voice_mail'?: string;
}

type SipPhoneEnableUserSipPhoneResponseTransportProtocolEnum = 'UDP' | 'TCP' | 'TLS' | 'AUTO'
type SipPhoneEnableUserSipPhoneResponseTransportProtocol2Enum = 'UDP' | 'TCP' | 'TLS' | 'AUTO'
type SipPhoneEnableUserSipPhoneResponseTransportProtocol3Enum = 'UDP' | 'TCP' | 'TLS' | 'AUTO'


