/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The H.323/SIP device object.
 * @export
 * @interface TheH323SIPDeviceObject
 */
export interface TheH323SIPDeviceObject {
    /**
     * Device ID.
     * @type {string}
     * @memberof TheH323SIPDeviceObject
     */
    'id'?: string;
    /**
     * Device encryption:    `auto` - auto.    `yes` - yes.    `no` - no.
     * @type {string}
     * @memberof TheH323SIPDeviceObject
     */
    'encryption': TheH323SIPDeviceObjectEncryptionEnum;
    /**
     * Device IP.
     * @type {string}
     * @memberof TheH323SIPDeviceObject
     */
    'ip': string;
    /**
     * Device name.
     * @type {string}
     * @memberof TheH323SIPDeviceObject
     */
    'name': string;
    /**
     * Device protocol:    `H.323` - H.323.    `SIP` - SIP.
     * @type {string}
     * @memberof TheH323SIPDeviceObject
     */
    'protocol': TheH323SIPDeviceObjectProtocolEnum;
}

type TheH323SIPDeviceObjectEncryptionEnum = 'auto' | 'true' | 'false'
type TheH323SIPDeviceObjectProtocolEnum = 'H.323' | 'SIP'


