/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Tracking Field
 * @export
 * @interface TrackingFieldGetResponse
 */
export interface TrackingFieldGetResponse {
    /**
     * Tracking Field ID
     * @type {string}
     * @memberof TrackingFieldGetResponse
     */
    'id'?: string;
    /**
     * Label/ Name for the tracking field.
     * @type {string}
     * @memberof TrackingFieldGetResponse
     */
    'field'?: string;
    /**
     * Array of recommended values
     * @type {Array<string>}
     * @memberof TrackingFieldGetResponse
     */
    'recommended_values'?: Array<string>;
    /**
     * Tracking Field Required
     * @type {boolean}
     * @memberof TrackingFieldGetResponse
     */
    'required'?: boolean;
    /**
     * Tracking Field Visible
     * @type {boolean}
     * @memberof TrackingFieldGetResponse
     */
    'visible'?: boolean;
}

