/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TspGetAccountInfoResponseDialInNumbersInner } from './tsp-get-account-info-response-dial-in-numbers-inner';

/**
 * 
 * @export
 * @interface TspGetAccountInfoResponse
 */
export interface TspGetAccountInfoResponse {
    /**
     * Control restriction on account users adding a TSP number outside of account\'s dial in numbers.
     * @type {boolean}
     * @memberof TspGetAccountInfoResponse
     */
    'dial_in_number_unrestricted'?: boolean;
    /**
     * 
     * @type {Array<TspGetAccountInfoResponseDialInNumbersInner>}
     * @memberof TspGetAccountInfoResponse
     */
    'dial_in_numbers'?: Array<TspGetAccountInfoResponseDialInNumbersInner>;
    /**
     * Enable Telephony Service Provider for account users.
     * @type {boolean}
     * @memberof TspGetAccountInfoResponse
     */
    'enable'?: boolean;
    /**
     * For master account, extend its TSP setting to all sub accounts. For sub account, extend TSP setting from master account.
     * @type {boolean}
     * @memberof TspGetAccountInfoResponse
     */
    'master_account_setting_extended'?: boolean;
    /**
     * Control restriction on account users being able to modify their TSP credentials.
     * @type {boolean}
     * @memberof TspGetAccountInfoResponse
     */
    'modify_credential_forbidden'?: boolean;
    /**
     * Telephony bridge zone
     * @type {string}
     * @memberof TspGetAccountInfoResponse
     */
    'tsp_bridge'?: TspGetAccountInfoResponseTspBridgeEnum;
    /**
     * Enable TSP feature for account. This has to be enabled to use any other tsp settings/features.
     * @type {boolean}
     * @memberof TspGetAccountInfoResponse
     */
    'tsp_enabled'?: boolean;
    /**
     * Telephony Service Provider.
     * @type {string}
     * @memberof TspGetAccountInfoResponse
     */
    'tsp_provider'?: string;
}

type TspGetAccountInfoResponseTspBridgeEnum = 'US_TSP_TB' | 'EU_TSP_TB'


