/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TspAddUserTspAccountResponseDialInNumbersInner } from './tsp-add-user-tsp-account-response-dial-in-numbers-inner';

/**
 * List of TSP accounts.
 * @export
 * @interface TspAddUserTspAccountResponse
 */
export interface TspAddUserTspAccountResponse {
    /**
     * The ID of the TSP account.
     * @type {string}
     * @memberof TspAddUserTspAccountResponse
     */
    'id'?: string;
    /**
     * Conference code: numeric value, length is less than 16.
     * @type {string}
     * @memberof TspAddUserTspAccountResponse
     */
    'conference_code': string;
    /**
     * List of dial in numbers.
     * @type {Array<TspAddUserTspAccountResponseDialInNumbersInner>}
     * @memberof TspAddUserTspAccountResponse
     */
    'dial_in_numbers'?: Array<TspAddUserTspAccountResponseDialInNumbersInner>;
    /**
     * Leader PIN: numeric value, length is less than 16.
     * @type {string}
     * @memberof TspAddUserTspAccountResponse
     */
    'leader_pin': string;
    /**
     * Telephony bridge
     * @type {string}
     * @memberof TspAddUserTspAccountResponse
     */
    'tsp_bridge'?: TspAddUserTspAccountResponseTspBridgeEnum;
}

type TspAddUserTspAccountResponseTspBridgeEnum = 'US_TSP_TB' | 'EU_TSP_TB'


