/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TspUpdateUserTspAccountRequestDialInNumbersInner
 */
export interface TspUpdateUserTspAccountRequestDialInNumbersInner {
    /**
     * Country code.
     * @type {string}
     * @memberof TspUpdateUserTspAccountRequestDialInNumbersInner
     */
    'code'?: string;
    /**
     * Country Label, if passed, will display in place of code.
     * @type {string}
     * @memberof TspUpdateUserTspAccountRequestDialInNumbersInner
     */
    'country_label'?: string;
    /**
     * Dial-in number: length is less than 16.
     * @type {string}
     * @memberof TspUpdateUserTspAccountRequestDialInNumbersInner
     */
    'number'?: string;
    /**
     * Dial-in number types:    `toll` - Toll number.    `tollfree` -Toll free number.    `media_link` - Media Link Phone Number. It is used for PSTN integration instead of paid bridge number.
     * @type {string}
     * @memberof TspUpdateUserTspAccountRequestDialInNumbersInner
     */
    'type'?: TspUpdateUserTspAccountRequestDialInNumbersInnerTypeEnum;
}

type TspUpdateUserTspAccountRequestDialInNumbersInnerTypeEnum = 'toll' | 'tollfree' | 'media_link'


