/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TspAddUserTspAccountResponseDialInNumbersInner
 */
export interface TspAddUserTspAccountResponseDialInNumbersInner {
    /**
     * Country code.
     * @type {string}
     * @memberof TspAddUserTspAccountResponseDialInNumbersInner
     */
    'code'?: string;
    /**
     * Country Label, if passed, will display in place of code.
     * @type {string}
     * @memberof TspAddUserTspAccountResponseDialInNumbersInner
     */
    'country_label'?: string;
    /**
     * Dial-in number: length is less than 16.
     * @type {string}
     * @memberof TspAddUserTspAccountResponseDialInNumbersInner
     */
    'number'?: string;
    /**
     * Dial-in number types:    `toll` - Toll number.    `tollfree` -Toll free number.     `media_link` - Media link.
     * @type {string}
     * @memberof TspAddUserTspAccountResponseDialInNumbersInner
     */
    'type'?: TspAddUserTspAccountResponseDialInNumbersInnerTypeEnum;
}

type TspAddUserTspAccountResponseDialInNumbersInnerTypeEnum = 'toll' | 'tollfree' | 'media_link'


