/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TspListUserTspAccountsUserIdParameterOneOf } from './tsp-list-user-tsp-accounts-user-id-parameter-one-of';

/**
 * @type TspListUserTspAccountsUserIdParameter
 * @export
 */
export type TspListUserTspAccountsUserIdParameter = TspListUserTspAccountsUserIdParameterOneOf | string;


