/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TSPAccountsListDialInNumbersInner } from './tspaccounts-list-dial-in-numbers-inner';

/**
 * List of TSP accounts.
 * @export
 * @interface TSPAccountsList
 */
export interface TSPAccountsList {
    /**
     * Conference code: numeric value, length is less than 16.
     * @type {string}
     * @memberof TSPAccountsList
     */
    'conference_code': string;
    /**
     * List of dial in numbers.
     * @type {Array<TSPAccountsListDialInNumbersInner>}
     * @memberof TSPAccountsList
     */
    'dial_in_numbers'?: Array<TSPAccountsListDialInNumbersInner>;
    /**
     * The TSP credential ID.
     * @type {string}
     * @memberof TSPAccountsList
     */
    'id'?: TSPAccountsListIdEnum;
    /**
     * Leader PIN: numeric value, length is less than 16.
     * @type {string}
     * @memberof TSPAccountsList
     */
    'leader_pin': string;
    /**
     * Telephony bridge 
     * @type {string}
     * @memberof TSPAccountsList
     */
    'tsp_bridge'?: TSPAccountsListTspBridgeEnum;
}

type TSPAccountsListIdEnum = '1' | '2'
type TSPAccountsListTspBridgeEnum = 'US_TSP_TB' | 'EU_TSP_TB'


