/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebinarsCreateBatchRegistrantsRequestRegistrantsInner
 */
export interface WebinarsCreateBatchRegistrantsRequestRegistrantsInner {
    /**
     * The registrant\'s email address.
     * @type {string}
     * @memberof WebinarsCreateBatchRegistrantsRequestRegistrantsInner
     */
    'email': string;
    /**
     * The registrant\'s first name.
     * @type {string}
     * @memberof WebinarsCreateBatchRegistrantsRequestRegistrantsInner
     */
    'first_name': string;
    /**
     * The registrant\'s last name.
     * @type {string}
     * @memberof WebinarsCreateBatchRegistrantsRequestRegistrantsInner
     */
    'last_name'?: string;
}

