/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Webinar live stream.
 * @export
 * @interface WebinarsUpdateLiveStreamRequest
 */
export interface WebinarsUpdateLiveStreamRequest {
    /**
     * The webinar live stream page\'s URL.
     * @type {string}
     * @memberof WebinarsUpdateLiveStreamRequest
     */
    'page_url': string;
    /**
     * The webinar live stream name and key.
     * @type {string}
     * @memberof WebinarsUpdateLiveStreamRequest
     */
    'stream_key': string;
    /**
     * The webinar live stream URL.
     * @type {string}
     * @memberof WebinarsUpdateLiveStreamRequest
     */
    'stream_url': string;
    /**
     * The number of pixels in each dimension that the video camera can display, required when a user enables 1080p. Use a value of `720p` or `1080p`
     * @type {string}
     * @memberof WebinarsUpdateLiveStreamRequest
     */
    'resolution'?: string;
}

