/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebinarsUpdateRegistrantStatusRequestRegistrantsInner
 */
export interface WebinarsUpdateRegistrantStatusRequestRegistrantsInner {
    /**
     * The registrant\'s email address.
     * @type {string}
     * @memberof WebinarsUpdateRegistrantStatusRequestRegistrantsInner
     */
    'email'?: string;
    /**
     * The registrant\'s ID.
     * @type {string}
     * @memberof WebinarsUpdateRegistrantStatusRequestRegistrantsInner
     */
    'id'?: string;
}

