/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebinarsGetSurveyResponseCustomSurvey } from './webinars-get-survey-response-custom-survey';

/**
 * Information about the webinar survey.
 * @export
 * @interface WebinarsGetSurveyResponse
 */
export interface WebinarsGetSurveyResponse {
    /**
     * 
     * @type {WebinarsGetSurveyResponseCustomSurvey}
     * @memberof WebinarsGetSurveyResponse
     */
    'custom_survey'?: WebinarsGetSurveyResponseCustomSurvey;
    /**
     * Whether the **Show in the browser when the webinar ends** option is enabled.  * `true` - Enabled.  * `false` - Disabled.    This value defaults to `true`.
     * @type {boolean}
     * @memberof WebinarsGetSurveyResponse
     */
    'show_in_the_browser'?: boolean;
    /**
     * Whether the **Show the link on the follow-up email** option is enabled.  * `true` - Enabled.  * `false` - Disabled.    This value defaults to `false`.
     * @type {boolean}
     * @memberof WebinarsGetSurveyResponse
     */
    'show_in_the_follow_up_email'?: boolean;
    /**
     * The link to the third party webinar survey.
     * @type {string}
     * @memberof WebinarsGetSurveyResponse
     */
    'third_party_survey'?: string;
}

