/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebinarsAddPanelistsResponse
 */
export interface WebinarsAddPanelistsResponse {
    /**
     * Webinar Id.
     * @type {string}
     * @memberof WebinarsAddPanelistsResponse
     */
    'id'?: string;
    /**
     * The time when the panelist was added.
     * @type {string}
     * @memberof WebinarsAddPanelistsResponse
     */
    'updated_at'?: string;
}

