/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebinarsListWebinarsResponseWebinarsInner } from './webinars-list-webinars-response-webinars-inner';

/**
 * List of webinars.
 * @export
 * @interface WebinarsListWebinarsResponse
 */
export interface WebinarsListWebinarsResponse {
    /**
     * Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token\'s expiration period is 15 minutes.
     * @type {string}
     * @memberof WebinarsListWebinarsResponse
     */
    'next_page_token'?: string;
    /**
     * The number of pages returned for the request made.
     * @type {number}
     * @memberof WebinarsListWebinarsResponse
     */
    'page_count'?: number;
    /**
     * **Deprecated** We will no longer support this field in a future release. Instead, use the `next_page_token` for pagination.
     * @type {number}
     * @memberof WebinarsListWebinarsResponse
     * @deprecated
     */
    'page_number'?: number;
    /**
     * The number of records returned with a single API call.
     * @type {number}
     * @memberof WebinarsListWebinarsResponse
     */
    'page_size'?: number;
    /**
     * The total number of all the records available across pages.
     * @type {number}
     * @memberof WebinarsListWebinarsResponse
     */
    'total_records'?: number;
    /**
     * List of webinar objects.
     * @type {Array<WebinarsListWebinarsResponseWebinarsInner>}
     * @memberof WebinarsListWebinarsResponse
     */
    'webinars'?: Array<WebinarsListWebinarsResponseWebinarsInner>;
}

