/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about the webinar\'s [Wallpaper] file.
 * @export
 * @interface WebinarsGetSessionBrandingResponseWallpaper
 */
export interface WebinarsGetSessionBrandingResponseWallpaper {
    /**
     * The wallpaper\'s file ID.
     * @type {string}
     * @memberof WebinarsGetSessionBrandingResponseWallpaper
     */
    'id'?: string;
}

