/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebinarsAddRegistrantRequestCustomQuestionsInner } from './webinars-add-registrant-request-custom-questions-inner';

/**
 * Information about the webinar registrant.
 * @export
 * @interface WebinarsAddRegistrantRequest
 */
export interface WebinarsAddRegistrantRequest {
    /**
     * The registrant\'s first name.
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'first_name': string;
    /**
     * The registrant\'s last name.
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'last_name'?: string;
    /**
     * The registrant\'s email address.
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'email': string;
    /**
     * The registrant\'s address.
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'address'?: string;
    /**
     * The registrant\'s city.
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'city'?: string;
    /**
     * The registrant\'s state or province.
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'state'?: string;
    /**
     * The registrant\'s ZIP or postal code.
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'zip'?: string;
    /**
     * The registrant\'s two-letter [country code](https://developers.zoom.us/docs/api/rest/other-references/abbreviation-lists/#countries).
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'country'?: string;
    /**
     * The registrant\'s phone number.
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'phone'?: string;
    /**
     * The registrant\'s questions and comments.
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'comments'?: string;
    /**
     * Information about custom questions.
     * @type {Array<WebinarsAddRegistrantRequestCustomQuestionsInner>}
     * @memberof WebinarsAddRegistrantRequest
     */
    'custom_questions'?: Array<WebinarsAddRegistrantRequestCustomQuestionsInner>;
    /**
     * The registrant\'s industry.
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'industry'?: string;
    /**
     * The registrant\'s job title.
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'job_title'?: string;
    /**
     * The registrant\'s number of employees:  * `1-20`  * `21-50`  * `51-100`  * `101-500`  * `500-1,000`  * `1,001-5,000`  * `5,001-10,000`  * `More than 10,000`
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'no_of_employees'?: WebinarsAddRegistrantRequestNoOfEmployeesEnum;
    /**
     * The registrant\'s organization.
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'org'?: string;
    /**
     * The registrant\'s purchasing time frame:  * `Within a month`  * `1-3 months`  * `4-6 months`  * `More than 6 months`  * `No timeframe`
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'purchasing_time_frame'?: WebinarsAddRegistrantRequestPurchasingTimeFrameEnum;
    /**
     * The registrant\'s role in the purchase process:  * `Decision Maker`  * `Evaluator/Recommender`  * `Influencer`  * `Not involved`
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'role_in_purchase_process'?: WebinarsAddRegistrantRequestRoleInPurchaseProcessEnum;
    /**
     * The registrant\'s language preference for confirmation emails:  * `en-US` - English (US)  * `de-DE` - German (Germany)  * `es-ES` - Spanish (Spain)  * `fr-FR` - French (France)  * `jp-JP` - Japanese  * `pt-PT` - Portuguese (Portugal)  * `ru-RU` - Russian  * `zh-CN` - Chinese (PRC)  * `zh-TW` - Chinese (Taiwan)  * `ko-KO` - Korean  * `it-IT` - Italian (Italy)  * `vi-VN` - Vietnamese  * `pl-PL` - Polish  * `Tr-TR` - Turkish
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'language'?: WebinarsAddRegistrantRequestLanguageEnum;
    /**
     * The tracking source\'s unique identifier.
     * @type {string}
     * @memberof WebinarsAddRegistrantRequest
     */
    'source_id'?: string;
}

type WebinarsAddRegistrantRequestNoOfEmployeesEnum = '' | '1-20' | '21-50' | '51-100' | '101-500' | '500-1,000' | '1,001-5,000' | '5,001-10,000' | 'More than 10,000'
type WebinarsAddRegistrantRequestPurchasingTimeFrameEnum = '' | 'Within a month' | '1-3 months' | '4-6 months' | 'More than 6 months' | 'No timeframe'
type WebinarsAddRegistrantRequestRoleInPurchaseProcessEnum = '' | 'Decision Maker' | 'Evaluator/Recommender' | 'Influencer' | 'Not involved'
type WebinarsAddRegistrantRequestLanguageEnum = 'en-US' | 'de-DE' | 'es-ES' | 'fr-FR' | 'jp-JP' | 'pt-PT' | 'ru-RU' | 'zh-CN' | 'zh-TW' | 'ko-KO' | 'it-IT' | 'vi-VN' | 'pl-PL' | 'Tr-TR'


