/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebinarsListRegistrationQuestionsResponseCustomQuestionsInner } from './webinars-list-registration-questions-response-custom-questions-inner';
import { WebinarsListRegistrationQuestionsResponseQuestionsInner } from './webinars-list-registration-questions-response-questions-inner';

/**
 * Webinar Registrant Questions
 * @export
 * @interface WebinarsListRegistrationQuestionsResponse
 */
export interface WebinarsListRegistrationQuestionsResponse {
    /**
     * Array of Registrant Custom Questions.
     * @type {Array<WebinarsListRegistrationQuestionsResponseCustomQuestionsInner>}
     * @memberof WebinarsListRegistrationQuestionsResponse
     */
    'custom_questions'?: Array<WebinarsListRegistrationQuestionsResponseCustomQuestionsInner>;
    /**
     * Array of registration fields whose values should be provided by registrants during registration.
     * @type {Array<WebinarsListRegistrationQuestionsResponseQuestionsInner>}
     * @memberof WebinarsListRegistrationQuestionsResponse
     */
    'questions'?: Array<WebinarsListRegistrationQuestionsResponseQuestionsInner>;
}

