/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebinarsUpdateRegistrationQuestionsRequestCustomQuestionsInner
 */
export interface WebinarsUpdateRegistrationQuestionsRequestCustomQuestionsInner {
    /**
     * Custom question.
     * @type {string}
     * @memberof WebinarsUpdateRegistrationQuestionsRequestCustomQuestionsInner
     */
    'title'?: string;
    /**
     * An array of answer choices. Can\'t be used for short answer type.
     * @type {Array<string>}
     * @memberof WebinarsUpdateRegistrationQuestionsRequestCustomQuestionsInner
     */
    'answers'?: Array<string>;
    /**
     * State whether or not a registrant is required to answer the custom question.
     * @type {boolean}
     * @memberof WebinarsUpdateRegistrationQuestionsRequestCustomQuestionsInner
     */
    'required'?: boolean;
    /**
     * The question-answer type.
     * @type {string}
     * @memberof WebinarsUpdateRegistrationQuestionsRequestCustomQuestionsInner
     */
    'type'?: WebinarsUpdateRegistrationQuestionsRequestCustomQuestionsInnerTypeEnum;
}

type WebinarsUpdateRegistrationQuestionsRequestCustomQuestionsInnerTypeEnum = 'short' | 'single_radio' | 'single_dropdown' | 'multiple'


