/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebinarsListAbsenteesResponseRegistrantsInner } from './webinars-list-absentees-response-registrants-inner';

/**
 * List of users.
 * @export
 * @interface WebinarsListAbsenteesResponse
 */
export interface WebinarsListAbsenteesResponse {
    /**
     * Use the next page token to paginate through large result sets. A next page token is returned whenever the set of available results exceeds the current page size. This token\'s expiration period is 15 minutes.
     * @type {string}
     * @memberof WebinarsListAbsenteesResponse
     */
    'next_page_token'?: string;
    /**
     * The number of pages returned for the request made.
     * @type {number}
     * @memberof WebinarsListAbsenteesResponse
     */
    'page_count'?: number;
    /**
     * **Deprecated.** This field is deprecated. We will no longer support this field in a future release. Instead, use the `next_page_token` for pagination.
     * @type {number}
     * @memberof WebinarsListAbsenteesResponse
     * @deprecated
     */
    'page_number'?: number;
    /**
     * The number of records returned with a single API call.
     * @type {number}
     * @memberof WebinarsListAbsenteesResponse
     */
    'page_size'?: number;
    /**
     * The total number of all the records available across pages.
     * @type {number}
     * @memberof WebinarsListAbsenteesResponse
     */
    'total_records'?: number;
    /**
     * List of registrant objects.
     * @type {Array<WebinarsListAbsenteesResponseRegistrantsInner>}
     * @memberof WebinarsListAbsenteesResponse
     */
    'registrants'?: Array<WebinarsListAbsenteesResponseRegistrantsInner>;
}

