/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebinarsCreateWebinarRequestSettingsSignLanguageInterpretationInterpretersInner } from './webinars-create-webinar-request-settings-sign-language-interpretation-interpreters-inner';

/**
 * The webinar\'s [sign language interpretation settings](https://support.zoom.us/hc/en-us/articles/9644962487309-Using-sign-language-interpretation-in-a-meeting-or-webinar). Make sure to add the language in the web portal in order to use it in the API. See link for details.   **Note:** If this feature is not enabled on the host\'s account, this setting will **not** be applied to the webinar.
 * @export
 * @interface WebinarsCreateWebinarRequestSettingsSignLanguageInterpretation
 */
export interface WebinarsCreateWebinarRequestSettingsSignLanguageInterpretation {
    /**
     * Whether to enable [sign language interpretation](https://support.zoom.us/hc/en-us/articles/9644962487309-Using-sign-language-interpretation-in-a-meeting-or-webinar) for the webinar.
     * @type {boolean}
     * @memberof WebinarsCreateWebinarRequestSettingsSignLanguageInterpretation
     */
    'enable'?: boolean;
    /**
     * Information about the webinar\'s sign language interpreters.
     * @type {Array<WebinarsCreateWebinarRequestSettingsSignLanguageInterpretationInterpretersInner>}
     * @memberof WebinarsCreateWebinarRequestSettingsSignLanguageInterpretation
     */
    'interpreters'?: Array<WebinarsCreateWebinarRequestSettingsSignLanguageInterpretationInterpretersInner>;
}

