/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebinarsRegistrantDetailsResponseCustomQuestionsInner } from './webinars-registrant-details-response-custom-questions-inner';

/**
 * Webinar registrant.
 * @export
 * @interface WebinarsRegistrantDetailsResponse
 */
export interface WebinarsRegistrantDetailsResponse {
    /**
     * 
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'id'?: string;
    /**
     * The registrant\'s address.
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'address'?: string;
    /**
     * The registrant\'s city.
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'city'?: string;
    /**
     * The registrant\'s questions and comments.
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'comments'?: string;
    /**
     * The registrant\'s two-letter ISO [country code](https://developers.zoom.us/docs/api/rest/other-references/abbreviation-lists/#countries).
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'country'?: string;
    /**
     * Information about custom questions.
     * @type {Array<WebinarsRegistrantDetailsResponseCustomQuestionsInner>}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'custom_questions'?: Array<WebinarsRegistrantDetailsResponseCustomQuestionsInner>;
    /**
     * The registrant\'s email address. See [Email address display rules](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#email-address-display-rules) for return value details.
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'email': string;
    /**
     * The registrant\'s first name.
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'first_name': string;
    /**
     * The registrant\'s industry.
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'industry'?: string;
    /**
     * The registrant\'s job title.
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'job_title'?: string;
    /**
     * The registrant\'s last name.
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'last_name'?: string;
    /**
     * The registrant\'s number of employees:  * `1-20`  * `21-50`  * `51-100`  * `101-250`  * `251-500`  * `501-1,000`  * `1,001-5,000`  * `5,001-10,000`  * `More than 10,000`
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'no_of_employees'?: WebinarsRegistrantDetailsResponseNoOfEmployeesEnum;
    /**
     * The registrant\'s organization.
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'org'?: string;
    /**
     * The registrant\'s phone number.
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'phone'?: string;
    /**
     * The registrant\'s purchasing time frame:  * `Within a month`  * `1-3 months`  * `4-6 months`  * `More than 6 months`  * `No timeframe`
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'purchasing_time_frame'?: WebinarsRegistrantDetailsResponsePurchasingTimeFrameEnum;
    /**
     * The registrant\'s role in the purchase process:  * `Decision Maker`  * `Evaluator/Recommender`  * `Influencer`  * `Not involved`
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'role_in_purchase_process'?: WebinarsRegistrantDetailsResponseRoleInPurchaseProcessEnum;
    /**
     * The registrant\'s state or province.
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'state'?: string;
    /**
     * The registrant\'s status:  * `approved` &mdash; Registrant is approved.  * `denied` &mdash; Registrant is denied.  * `pending` &mdash; Registrant is waiting for approval.
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'status'?: WebinarsRegistrantDetailsResponseStatusEnum;
    /**
     * The registrant\'s ZIP or postal code.
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'zip'?: string;
    /**
     * The registrant\'s language preference for confirmation emails:  * `en-US` &mdash; English (US)  * `de-DE` &mdash; German (Germany)  * `es-ES` &mdash; Spanish (Spain)  * `fr-FR` &mdash; French (France)  * `jp-JP` &mdash; Japanese  * `pt-PT` &mdash; Portuguese (Portugal)  * `ru-RU` &mdash; Russian  * `zh-CN` &mdash; Chinese (PRC)  * `zh-TW` &mdash; Chinese (Taiwan)  * `ko-KO` &mdash; Korean  * `it-IT` &mdash; Italian (Italy)  * `vi-VN` &mdash; Vietnamese  * `pl-PL` &mdash; Polish  * `Tr-TR` &mdash; Turkish
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'language'?: WebinarsRegistrantDetailsResponseLanguageEnum;
    /**
     * 
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'create_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof WebinarsRegistrantDetailsResponse
     */
    'join_url'?: string;
}

type WebinarsRegistrantDetailsResponseNoOfEmployeesEnum = '' | '1-20' | '21-50' | '51-100' | '101-250' | '251-500' | '501-1,000' | '1,001-5,000' | '5,001-10,000' | 'More than 10,000'
type WebinarsRegistrantDetailsResponsePurchasingTimeFrameEnum = '' | 'Within a month' | '1-3 months' | '4-6 months' | 'More than 6 months' | 'No timeframe'
type WebinarsRegistrantDetailsResponseRoleInPurchaseProcessEnum = '' | 'Decision Maker' | 'Evaluator/Recommender' | 'Influencer' | 'Not involved'
type WebinarsRegistrantDetailsResponseStatusEnum = 'approved' | 'denied' | 'pending'
type WebinarsRegistrantDetailsResponseLanguageEnum = 'en-US' | 'de-DE' | 'es-ES' | 'fr-FR' | 'jp-JP' | 'pt-PT' | 'ru-RU' | 'zh-CN' | 'zh-TW' | 'ko-KO' | 'it-IT' | 'vi-VN' | 'pl-PL' | 'Tr-TR'


