/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebinarsGetSessionBrandingResponseNameTagsInner } from './webinars-get-session-branding-response-name-tags-inner';
import { WebinarsGetSessionBrandingResponseVirtualBackgroundsInner } from './webinars-get-session-branding-response-virtual-backgrounds-inner';
import { WebinarsGetSessionBrandingResponseWallpaper } from './webinars-get-session-branding-response-wallpaper';

/**
 * Information about the webinar\'s sessions branding.
 * @export
 * @interface WebinarsGetSessionBrandingResponse
 */
export interface WebinarsGetSessionBrandingResponse {
    /**
     * 
     * @type {WebinarsGetSessionBrandingResponseWallpaper}
     * @memberof WebinarsGetSessionBrandingResponse
     */
    'wallpaper'?: WebinarsGetSessionBrandingResponseWallpaper;
    /**
     * Information about the webinar\'s [Virtual Background](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background) files.
     * @type {Array<WebinarsGetSessionBrandingResponseVirtualBackgroundsInner>}
     * @memberof WebinarsGetSessionBrandingResponse
     */
    'virtual_backgrounds'?: Array<WebinarsGetSessionBrandingResponseVirtualBackgroundsInner>;
    /**
     * Information about the webinar\'s name tag.
     * @type {Array<WebinarsGetSessionBrandingResponseNameTagsInner>}
     * @memberof WebinarsGetSessionBrandingResponse
     */
    'name_tags'?: Array<WebinarsGetSessionBrandingResponseNameTagsInner>;
}

