/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebinarsUploadBrandingVirtualBackgroundResponse
 */
export interface WebinarsUploadBrandingVirtualBackgroundResponse {
    /**
     * The Virtual Background file\'s ID.
     * @type {string}
     * @memberof WebinarsUploadBrandingVirtualBackgroundResponse
     */
    'id'?: string;
    /**
     * The Virtual Background file\'s name.
     * @type {string}
     * @memberof WebinarsUploadBrandingVirtualBackgroundResponse
     */
    'name'?: string;
    /**
     * Whether the file is the default Virtual Background file.
     * @type {boolean}
     * @memberof WebinarsUploadBrandingVirtualBackgroundResponse
     */
    'is_default'?: boolean;
    /**
     * The Virtual Background file\'s size, in bytes.
     * @type {number}
     * @memberof WebinarsUploadBrandingVirtualBackgroundResponse
     */
    'size'?: number;
    /**
     * The Virtual Background file\'s file type:  * `image` &mdash; An image file.
     * @type {string}
     * @memberof WebinarsUploadBrandingVirtualBackgroundResponse
     */
    'type'?: WebinarsUploadBrandingVirtualBackgroundResponseTypeEnum;
}

type WebinarsUploadBrandingVirtualBackgroundResponseTypeEnum = 'image'


