/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebinarsGetSessionBrandingResponseVirtualBackgroundsInner
 */
export interface WebinarsGetSessionBrandingResponseVirtualBackgroundsInner {
    /**
     * The Virtual Background\'s file ID.
     * @type {string}
     * @memberof WebinarsGetSessionBrandingResponseVirtualBackgroundsInner
     */
    'id'?: string;
    /**
     * The Virtual Background\'s file name.
     * @type {string}
     * @memberof WebinarsGetSessionBrandingResponseVirtualBackgroundsInner
     */
    'name'?: string;
    /**
     * Whether the file is the default Virtual Background file.
     * @type {boolean}
     * @memberof WebinarsGetSessionBrandingResponseVirtualBackgroundsInner
     */
    'is_default'?: boolean;
}

