/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebinarsUploadBrandingWallpaperResponse
 */
export interface WebinarsUploadBrandingWallpaperResponse {
    /**
     * The wallpaper file\'s ID.
     * @type {string}
     * @memberof WebinarsUploadBrandingWallpaperResponse
     */
    'id'?: string;
    /**
     * The wallpaper file\'s name.
     * @type {string}
     * @memberof WebinarsUploadBrandingWallpaperResponse
     */
    'name'?: string;
    /**
     * The wallpaper file\'s size, in bytes.
     * @type {number}
     * @memberof WebinarsUploadBrandingWallpaperResponse
     */
    'size'?: number;
    /**
     * The wallpaper file\'s file type:  * `image` &mdash; An image file.
     * @type {string}
     * @memberof WebinarsUploadBrandingWallpaperResponse
     */
    'type'?: WebinarsUploadBrandingWallpaperResponseTypeEnum;
}

type WebinarsUploadBrandingWallpaperResponseTypeEnum = 'image'


