/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebinarsListPastWebinarQaResponseQuestionsInner } from './webinars-list-past-webinar-qa-response-questions-inner';

/**
 * 
 * @export
 * @interface WebinarsListPastWebinarQaResponse
 */
export interface WebinarsListPastWebinarQaResponse {
    /**
     * Webinar ID in **long** format, represented as int64 data type in JSON, also known as the webinar number.
     * @type {number}
     * @memberof WebinarsListPastWebinarQaResponse
     */
    'id'?: number;
    /**
     * 
     * @type {Array<WebinarsListPastWebinarQaResponseQuestionsInner>}
     * @memberof WebinarsListPastWebinarQaResponse
     */
    'questions'?: Array<WebinarsListPastWebinarQaResponseQuestionsInner>;
    /**
     * The webinar\'s start time.
     * @type {string}
     * @memberof WebinarsListPastWebinarQaResponse
     */
    'start_time'?: string;
    /**
     * Webinar UUID.
     * @type {string}
     * @memberof WebinarsListPastWebinarQaResponse
     */
    'uuid'?: string;
}

