/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebinarsListWebinarTemplatesResponseTemplatesInner
 */
export interface WebinarsListWebinarTemplatesResponseTemplatesInner {
    /**
     * The webinar template\'s ID.
     * @type {string}
     * @memberof WebinarsListWebinarTemplatesResponseTemplatesInner
     */
    'id'?: string;
    /**
     * The webinar template\'s name.
     * @type {string}
     * @memberof WebinarsListWebinarTemplatesResponseTemplatesInner
     */
    'name'?: string;
    /**
     * The webinar template type.  `1`: Webinar template    `2`: Admin webinar template
     * @type {number}
     * @memberof WebinarsListWebinarTemplatesResponseTemplatesInner
     */
    'type'?: number;
}

