/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about the webinar\'s local archive token.
 * @export
 * @interface WebinarsGetMeetingArchiveTokenForLocalArchivingResponse
 */
export interface WebinarsGetMeetingArchiveTokenForLocalArchivingResponse {
    /**
     * The number of seconds the archive token is valid for before it expires. This value always returns `120`.
     * @type {number}
     * @memberof WebinarsGetMeetingArchiveTokenForLocalArchivingResponse
     */
    'expire_in'?: WebinarsGetMeetingArchiveTokenForLocalArchivingResponseExpireInEnum;
    /**
     * The archive token.
     * @type {string}
     * @memberof WebinarsGetMeetingArchiveTokenForLocalArchivingResponse
     */
    'token'?: string;
}

type WebinarsGetMeetingArchiveTokenForLocalArchivingResponseExpireInEnum = 120


