/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Panelist base object.
 * @export
 * @interface WebinarsAddPanelistsRequestPanelistsInner
 */
export interface WebinarsAddPanelistsRequestPanelistsInner {
    /**
     * Panelist\'s email. See the [email address display rules](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#email-address-display-rules) for return value details.
     * @type {string}
     * @memberof WebinarsAddPanelistsRequestPanelistsInner
     */
    'email'?: string;
    /**
     * The panelist\'s full name.  **Note:** This value cannot exceed more than 12 Chinese characters.
     * @type {string}
     * @memberof WebinarsAddPanelistsRequestPanelistsInner
     */
    'name'?: string;
    /**
     * The virtual background ID to bind.
     * @type {string}
     * @memberof WebinarsAddPanelistsRequestPanelistsInner
     */
    'virtual_background_id'?: string;
    /**
     * The name tag ID to bind.
     * @type {string}
     * @memberof WebinarsAddPanelistsRequestPanelistsInner
     */
    'name_tag_id'?: string;
    /**
     * The panelist\'s name to display in the name tag.
     * @type {string}
     * @memberof WebinarsAddPanelistsRequestPanelistsInner
     */
    'name_tag_name'?: string;
    /**
     * The pronouns to display in the name tag.
     * @type {string}
     * @memberof WebinarsAddPanelistsRequestPanelistsInner
     */
    'name_tag_pronouns'?: string;
    /**
     * The description for the name tag, such the person\'s title.
     * @type {string}
     * @memberof WebinarsAddPanelistsRequestPanelistsInner
     */
    'name_tag_description'?: string;
}

