/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebinarsCreatePollResponseQuestionsInner } from './webinars-create-poll-response-questions-inner';

/**
 * Information about meeting and webinar polling.
 * @export
 * @interface WebinarsCreatePollResponse
 */
export interface WebinarsCreatePollResponse {
    /**
     * The poll\'s title, up to 64 characters.
     * @type {string}
     * @memberof WebinarsCreatePollResponse
     */
    'title'?: string;
    /**
     * Webinar Poll ID
     * @type {string}
     * @memberof WebinarsCreatePollResponse
     */
    'id'?: string;
    /**
     * Status of the Webinar Poll:    `notstart` - Poll not started    `started` - Poll started    `ended` - Poll ended    `sharing` - Sharing poll results
     * @type {string}
     * @memberof WebinarsCreatePollResponse
     */
    'status'?: WebinarsCreatePollResponseStatusEnum;
    /**
     * Allow meeting participants to answer poll questions anonymously.   This value defaults to `false`.
     * @type {boolean}
     * @memberof WebinarsCreatePollResponse
     */
    'anonymous'?: boolean;
    /**
     * The type of poll.  * `1` - Poll.  * `2` - Advanced Poll. This feature must be enabled in your Zoom account.  * `3` - Quiz. This feature must be enabled in your Zoom account.    This value defaults to `1`.
     * @type {number}
     * @memberof WebinarsCreatePollResponse
     */
    'poll_type'?: WebinarsCreatePollResponsePollTypeEnum;
    /**
     * Information about the poll\'s questions.
     * @type {Array<WebinarsCreatePollResponseQuestionsInner>}
     * @memberof WebinarsCreatePollResponse
     */
    'questions'?: Array<WebinarsCreatePollResponseQuestionsInner>;
}

type WebinarsCreatePollResponseStatusEnum = 'notstart' | 'started' | 'ended' | 'sharing'
type WebinarsCreatePollResponsePollTypeEnum = 1 | 2 | 3


