/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebinarsUpdateScheduledWebinarRequestSettingsLanguageInterpretationInterpretersInner } from './webinars-update-scheduled-webinar-request-settings-language-interpretation-interpreters-inner';

/**
 * The webinar\'s [language interpretation settings](https://support.zoom.us/hc/en-us/articles/360034919791-Language-interpretation-in-meetings-and-webinars). Make sure to add the language in the web portal in order to use it in the API. See link for details.   **Note** This feature is only available for certain webinar add-ons, and for Education, and Business, and higher plans. If this feature is not enabled on the host\'s account, this setting will **not** be applied to the webinar.
 * @export
 * @interface WebinarsUpdateScheduledWebinarRequestSettingsLanguageInterpretation
 */
export interface WebinarsUpdateScheduledWebinarRequestSettingsLanguageInterpretation {
    /**
     * Enable [language interpretation](https://support.zoom.us/hc/en-us/articles/360034919791-Language-interpretation-in-meetings-and-webinars) for the webinar.
     * @type {boolean}
     * @memberof WebinarsUpdateScheduledWebinarRequestSettingsLanguageInterpretation
     */
    'enable'?: boolean;
    /**
     * Information about the webinar\'s language interpreters.
     * @type {Array<WebinarsUpdateScheduledWebinarRequestSettingsLanguageInterpretationInterpretersInner>}
     * @memberof WebinarsUpdateScheduledWebinarRequestSettingsLanguageInterpretation
     */
    'interpreters'?: Array<WebinarsUpdateScheduledWebinarRequestSettingsLanguageInterpretationInterpretersInner>;
}

