/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebinarsListTrackingSourcesResponseTrackingSourcesInner } from './webinars-list-tracking-sources-response-tracking-sources-inner';

/**
 * 
 * @export
 * @interface WebinarsListTrackingSourcesResponse
 */
export interface WebinarsListTrackingSourcesResponse {
    /**
     * The total number of registration records for this Webinar.
     * @type {number}
     * @memberof WebinarsListTrackingSourcesResponse
     */
    'total_records'?: number;
    /**
     * Tracking Sources object.
     * @type {Array<WebinarsListTrackingSourcesResponseTrackingSourcesInner>}
     * @memberof WebinarsListTrackingSourcesResponse
     */
    'tracking_sources'?: Array<WebinarsListTrackingSourcesResponseTrackingSourcesInner>;
}

