/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebinarsGetSurveyResponseCustomSurveyQuestionsInner } from './webinars-get-survey-response-custom-survey-questions-inner';

/**
 * Information about the customized webinar survey.
 * @export
 * @interface WebinarsGetSurveyResponseCustomSurvey
 */
export interface WebinarsGetSurveyResponseCustomSurvey {
    /**
     * The survey\'s title, up to 64 characters.
     * @type {string}
     * @memberof WebinarsGetSurveyResponseCustomSurvey
     */
    'title'?: string;
    /**
     * Allow participants to anonymously answer survey questions.  * `true` - Anonymous survey enabled.  * `false` - Participants cannot answer survey questions anonymously.    This value defaults to `true`.
     * @type {boolean}
     * @memberof WebinarsGetSurveyResponseCustomSurvey
     */
    'anonymous'?: boolean;
    /**
     * Whether to display the number in the question name.    This value defaults to `true`.
     * @type {boolean}
     * @memberof WebinarsGetSurveyResponseCustomSurvey
     */
    'numbered_questions'?: boolean;
    /**
     * Whether to display the question type in the question name.    This value defaults to `false`.
     * @type {boolean}
     * @memberof WebinarsGetSurveyResponseCustomSurvey
     */
    'show_question_type'?: boolean;
    /**
     * The survey\'s feedback, up to 320 characters.    This value defaults to `Thank you so much for taking the time to complete the survey, your feedback really makes a difference.`.
     * @type {string}
     * @memberof WebinarsGetSurveyResponseCustomSurvey
     */
    'feedback'?: string;
    /**
     * Information about the webinar survey\'s questions.
     * @type {Array<WebinarsGetSurveyResponseCustomSurveyQuestionsInner>}
     * @memberof WebinarsGetSurveyResponseCustomSurvey
     */
    'questions'?: Array<WebinarsGetSurveyResponseCustomSurveyQuestionsInner>;
}

