/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebinarsUpdateSurveyRequestCustomSurveyQuestionsInnerPromptsInner
 */
export interface WebinarsUpdateSurveyRequestCustomSurveyQuestionsInnerPromptsInner {
    /**
     * The question prompt\'s title.
     * @type {string}
     * @memberof WebinarsUpdateSurveyRequestCustomSurveyQuestionsInnerPromptsInner
     */
    'prompt_question'?: string;
}

