/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Update the live stream session\'s settings.  **Only** settings for a stopped live stream can be updated.
 * @export
 * @interface WebinarsUpdateLiveStreamStatusRequestSettings
 */
export interface WebinarsUpdateLiveStreamStatusRequestSettings {
    /**
     * Display the name of the active speaker during a live stream.
     * @type {boolean}
     * @memberof WebinarsUpdateLiveStreamStatusRequestSettings
     */
    'active_speaker_name'?: boolean;
    /**
     * Display the live stream\'s name.
     * @type {string}
     * @memberof WebinarsUpdateLiveStreamStatusRequestSettings
     */
    'display_name'?: string;
}

