/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebinarsGetLiveStreamDetailsResponse
 */
export interface WebinarsGetLiveStreamDetailsResponse {
    /**
     * Live streaming page URL. This is the URL using which anyone can view the live stream of the webinar.
     * @type {string}
     * @memberof WebinarsGetLiveStreamDetailsResponse
     */
    'page_url'?: string;
    /**
     * Stream key.
     * @type {string}
     * @memberof WebinarsGetLiveStreamDetailsResponse
     */
    'stream_key'?: string;
    /**
     * Stream URL.
     * @type {string}
     * @memberof WebinarsGetLiveStreamDetailsResponse
     */
    'stream_url'?: string;
    /**
     * The number of pixels in each dimension that the video camera can display.
     * @type {string}
     * @memberof WebinarsGetLiveStreamDetailsResponse
     */
    'resolution'?: string;
}

