/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebinarsCreateWebinarResponseTrackingFieldsInner
 */
export interface WebinarsCreateWebinarResponseTrackingFieldsInner {
    /**
     * Tracking fields type
     * @type {string}
     * @memberof WebinarsCreateWebinarResponseTrackingFieldsInner
     */
    'field'?: string;
    /**
     * Tracking fields value
     * @type {string}
     * @memberof WebinarsCreateWebinarResponseTrackingFieldsInner
     */
    'value'?: string;
}

