/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about the webinar\'s encoded SIP URI.
 * @export
 * @interface WebinarsGetSipUriWithPasscodeResponse
 */
export interface WebinarsGetSipUriWithPasscodeResponse {
    /**
     * The webinar\'s encoded SIP URI.
     * @type {string}
     * @memberof WebinarsGetSipUriWithPasscodeResponse
     */
    'sip_dialing'?: string;
    /**
     * Whether the API caller has a Conference Room Connector (CRC) plan.
     * @type {boolean}
     * @memberof WebinarsGetSipUriWithPasscodeResponse
     */
    'paid_crc_plan_participant'?: boolean;
    /**
     * This value identifies the webinar participant. It is automatically embedded in the SIP URI if the API caller has a CRC plan.
     * @type {string}
     * @memberof WebinarsGetSipUriWithPasscodeResponse
     */
    'participant_identifier_code'?: string;
    /**
     * The number of seconds the encoded SIP URI is valid before it expires.
     * @type {number}
     * @memberof WebinarsGetSipUriWithPasscodeResponse
     */
    'expire_in'?: number;
}

