/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebinarsCreateWebinarTemplateResponse
 */
export interface WebinarsCreateWebinarTemplateResponse {
    /**
     * The webinar template\'s ID.
     * @type {string}
     * @memberof WebinarsCreateWebinarTemplateResponse
     */
    'id'?: string;
    /**
     * The webinar template\'s name.
     * @type {string}
     * @memberof WebinarsCreateWebinarTemplateResponse
     */
    'name'?: string;
}

