/*
Zoom Meeting API

The Zoom Meeting APIs let developers to access information from Zoom. 

The version of the OpenAPI document: 2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebinarsListWebinarTemplatesResponseTemplatesInner } from './webinars-list-webinar-templates-response-templates-inner';

/**
 * 
 * @export
 * @interface WebinarsListWebinarTemplatesResponse
 */
export interface WebinarsListWebinarTemplatesResponse {
    /**
     * Information about the webinar templates.
     * @type {Array<WebinarsListWebinarTemplatesResponseTemplatesInner>}
     * @memberof WebinarsListWebinarTemplatesResponse
     */
    'templates'?: Array<WebinarsListWebinarTemplatesResponseTemplatesInner>;
    /**
     * The total number of records returned.
     * @type {number}
     * @memberof WebinarsListWebinarTemplatesResponse
     */
    'total_records'?: number;
}

